---
title: "Temporal_gr치ficos y otros"
author: "CEPAL"
date: "21/2/2022"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Tabla Zona Vs Sexo

```{r, tab2, eval=FALSE}
(
  prop_sexo_zona <- diseno %>%
    mutate(pobreza = ifelse(Poverty != "NotPoor",
                   "pobre", "no pobre" )) %>% 
    group_by(Sex, Zone, pobreza) %>%
    summarise(
      prop = survey_prop(vartype = c("se", "ci"))) %>% 
    data.frame()
)

```

## Tabla Zona Vs Sexo

```{r, tab2, echo = FALSE, eval = TRUE}
```


## Diagrama de barras Zona Vs Sexo

```{r, hist2, eval=FALSE}
require(ggplot2)
ggplot(data = prop_sexo_zona,
       aes(
         x = Zone,
         y = prop,
         ymax = prop_upp,
         ymin = prop_low,
         fill = Sex
       )) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(position = position_dodge(width = 0.9),
                width = 0.3)

```

## Diagrama de barras Zona Vs Sexo

```{r, hist2, echo = FALSE, eval = TRUE}
```




## glm del Zona en funci칩n del ingreso 

```{r, echo = TRUE, eval = TRUE}
mod <- svyglm(as.factor(Zone) ~ Income, 
              design=diseno, family=quasibinomial)
summary(mod)$coefficients
```

## glm del Zona en funci칩n del ingreso 

```{r, echo = TRUE, eval = TRUE}
mod2 <- svyglm(as.factor(Sex) ~ Income, 
               design=diseno, family=quasibinomial)
summary(mod2)$coefficients

```

```{r}
require(svydiags)
df_qq <- tibble(
  Empirica = Hmisc::wtd.quantile(
    x = svystdres(fit_svy_qwgt)$stdresids,
    weights = encuesta$wk2, 
    probs = seq(0.01,.99,len=1000) 
                      ),
Teorica = qnorm(p = seq(0.01,0.99,len=1000)))

par(mfrow = c(1,2))
ggplot(data = df_qq, aes(y = Empirica, x = Teorica)) +
  geom_point() +  geom_abline(slope = 1)
```


## Estimaci칩n del dato

$$
\hat{E}(y_{i}\mid\boldsymbol{x}_{obs,i})=\boldsymbol{x}_{obs,i}\hat{\boldsymbol{\beta}}\\
\hat{E}(y_{i}\mid\boldsymbol{x}_{obs,i})=\beta_{0}+\beta_{1}x_{1i}+\beta_{2}x_{2i}+\beta_{3}x_{3i}+\beta_{4}x_{4i}+\beta_{5}x_{5i} 
$$

```{r}
coef(mod_svy)
```

$$
\hat{E}(y_{i}\mid\boldsymbol{x}_{obs,i})=71.802 +1.089x_{1i}+47.618x_{2i}+9.199x_{3i}+1.174x_{4i}
$$

```{r}
 model.matrix(mod_svy) %>%
  as.data.frame()%>% slice(1:2)
```

$$
\hat{E}(y_{i}\mid\boldsymbol{x}_{obs,i})=71.802  +1.089(247.9)+47.618(0)+9.199(1)+1.174(55)
$$

