<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.8 Estimando contrastes en encuestas de hogares | Análisis de encuestas con R</title>
  <meta name="description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="4.8 Estimando contrastes en encuestas de hogares | Análisis de encuestas con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="github-repo" content="psirusteam/HHS-Handbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.8 Estimando contrastes en encuestas de hogares | Análisis de encuestas con R" />
  
  <meta name="twitter:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  

<meta name="author" content="Andrés Gutiérrez, Cristian Téllez, Stalyn Guerrero" />


<meta name="date" content="2023-03-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estimando-razones-en-encuestas-de-hogares.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis de encuestas con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="chapter" data-level="1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="conceptos-básicos-en-encuestas-de-hogares.html"><a href="conceptos-básicos-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>2</b> Conceptos básicos en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="universo-de-estudio-y-población-objetivo.html"><a href="universo-de-estudio-y-población-objetivo.html"><i class="fa fa-check"></i><b>2.1</b> Universo de estudio y población objetivo</a></li>
<li class="chapter" data-level="2.2" data-path="unidades-de-análisis.html"><a href="unidades-de-análisis.html"><i class="fa fa-check"></i><b>2.2</b> Unidades de análisis</a></li>
<li class="chapter" data-level="2.3" data-path="unidades-de-muestreo.html"><a href="unidades-de-muestreo.html"><i class="fa fa-check"></i><b>2.3</b> Unidades de muestreo</a></li>
<li class="chapter" data-level="2.4" data-path="marcos-de-muestreo.html"><a href="marcos-de-muestreo.html"><i class="fa fa-check"></i><b>2.4</b> Marcos de muestreo</a></li>
<li class="chapter" data-level="2.5" data-path="selección-de-una-muestra.html"><a href="selección-de-una-muestra.html"><i class="fa fa-check"></i><b>2.5</b> Selección de una muestra</a></li>
<li class="chapter" data-level="2.6" data-path="motivación.html"><a href="motivación.html"><i class="fa fa-check"></i><b>2.6</b> Motivación</a></li>
<li class="chapter" data-level="2.7" data-path="muestreo-aleatorio-simple-en-dos-etapas-estratificado.html"><a href="muestreo-aleatorio-simple-en-dos-etapas-estratificado.html"><i class="fa fa-check"></i><b>2.7</b> Muestreo aleatorio simple en dos etapas estratificado</a></li>
<li class="chapter" data-level="2.8" data-path="práctica-en-r.html"><a href="práctica-en-r.html"><i class="fa fa-check"></i><b>2.8</b> Práctica en <code>R</code></a></li>
<li class="chapter" data-level="2.9" data-path="calibrando-con-r.html"><a href="calibrando-con-r.html"><i class="fa fa-check"></i><b>2.9</b> Calibrando con <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manejando-una-base-de-encuestas-de-hogares-con-r.html"><a href="manejando-una-base-de-encuestas-de-hogares-con-r.html"><i class="fa fa-check"></i><b>3</b> Manejando una base de encuestas de hogares con R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="fundamentos-básicos-de-r-y-rstudio.html"><a href="fundamentos-básicos-de-r-y-rstudio.html"><i class="fa fa-check"></i><b>3.1</b> Fundamentos básicos de R y Rstudio</a></li>
<li class="chapter" data-level="3.2" data-path="algunas-librerías-de-interés.html"><a href="algunas-librerías-de-interés.html"><i class="fa fa-check"></i><b>3.2</b> Algunas librerías de interés</a></li>
<li class="chapter" data-level="3.3" data-path="cración-de-proyectos-en-r.html"><a href="cración-de-proyectos-en-r.html"><i class="fa fa-check"></i><b>3.3</b> Cración de proyectos en <code>R</code></a></li>
<li class="chapter" data-level="3.4" data-path="lectura-de-las-bases-de-datos-y-manipulación.html"><a href="lectura-de-las-bases-de-datos-y-manipulación.html"><i class="fa fa-check"></i><b>3.4</b> Lectura de las bases de datos y manipulación</a></li>
<li class="chapter" data-level="3.5" data-path="el-operador-pipe.html"><a href="el-operador-pipe.html"><i class="fa fa-check"></i><b>3.5</b> El operador <code>pipe</code></a></li>
<li class="chapter" data-level="3.6" data-path="funciones-mutate-summarise-y-group_by-en-encuestas-de-hogares.html"><a href="funciones-mutate-summarise-y-group_by-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>3.6</b> Funciones <strong>mutate, summarise y group_by</strong> en encuestas de hogares</a></li>
<li class="chapter" data-level="3.7" data-path="medidas-descriptivos-y-reflexiones.html"><a href="medidas-descriptivos-y-reflexiones.html"><i class="fa fa-check"></i><b>3.7</b> Medidas descriptivos y reflexiones</a></li>
<li class="chapter" data-level="3.8" data-path="algunas-reflexiones-generales.html"><a href="algunas-reflexiones-generales.html"><i class="fa fa-check"></i><b>3.8</b> Algunas reflexiones generales</a></li>
<li class="chapter" data-level="3.9" data-path="observación-importante.html"><a href="observación-importante.html"><i class="fa fa-check"></i><b>3.9</b> <strong>¡Observación importante!</strong></a></li>
<li class="chapter" data-level="3.10" data-path="medias-y-totales.html"><a href="medias-y-totales.html"><i class="fa fa-check"></i><b>3.10</b> Medias y totales</a></li>
<li class="chapter" data-level="3.11" data-path="medianas-y-percentiles.html"><a href="medianas-y-percentiles.html"><i class="fa fa-check"></i><b>3.11</b> Medianas y percentiles</a></li>
<li class="chapter" data-level="3.12" data-path="varianza-desviación-estándar-y-rangos.html"><a href="varianza-desviación-estándar-y-rangos.html"><i class="fa fa-check"></i><b>3.12</b> Varianza, desviación estándar y rangos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-de-las-variables-continuas-en-encuestas-de-hogares.html"><a href="análisis-de-las-variables-continuas-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4</b> Análisis de las variables continuas en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lectura-de-bases-de-datos-y-definición-del-diseño-muestral.html"><a href="lectura-de-bases-de-datos-y-definición-del-diseño-muestral.html"><i class="fa fa-check"></i><b>4.1</b> Lectura de bases de datos y definición del diseño muestral</a></li>
<li class="chapter" data-level="4.2" data-path="análisis-gráfico-histogramas-y-boxplot.html"><a href="análisis-gráfico-histogramas-y-boxplot.html"><i class="fa fa-check"></i><b>4.2</b> Análisis gráfico: Histogramas y Boxplot</a></li>
<li class="chapter" data-level="4.3" data-path="estimación-puntual.html"><a href="estimación-puntual.html"><i class="fa fa-check"></i><b>4.3</b> Estimación puntual</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-totales-e-intervalos-de-confianza"><i class="fa fa-check"></i><b>4.3.1</b> Estimación de totales e intervalos de confianza</a></li>
<li class="chapter" data-level="4.3.2" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-la-media-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.3.2</b> Estimación de la media e intervalo de confianza</a></li>
<li class="chapter" data-level="4.3.3" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-medidas-de-dispersión-y-localización"><i class="fa fa-check"></i><b>4.3.3</b> Estimación de medidas de dispersión y localización</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="estimación-del-coeficiente-de-ginni-en-encuestas-de-hogares.html"><a href="estimación-del-coeficiente-de-ginni-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.4</b> Estimación del coeficiente de Ginni en encuestas de hogares</a></li>
<li class="chapter" data-level="4.5" data-path="análisis-de-la-relación-entre-dos-variable-continuas.html"><a href="análisis-de-la-relación-entre-dos-variable-continuas.html"><i class="fa fa-check"></i><b>4.5</b> Análisis de la relación entre dos variable continuas</a></li>
<li class="chapter" data-level="4.6" data-path="prueba-de-hipótesis-para-la-diferencia-de-medias-en-encuestas-de-hogares.html"><a href="prueba-de-hipótesis-para-la-diferencia-de-medias-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.6</b> Prueba de hipótesis para la diferencia de medias en encuestas de hogares</a></li>
<li class="chapter" data-level="4.7" data-path="estimando-razones-en-encuestas-de-hogares.html"><a href="estimando-razones-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.7</b> Estimando razones en encuestas de hogares</a></li>
<li class="chapter" data-level="4.8" data-path="estimando-contrastes-en-encuestas-de-hogares.html"><a href="estimando-contrastes-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.8</b> Estimando contrastes en encuestas de hogares</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>5</b> Referencias</a></li>
<li class="divider"></li>
<li><a Análisis de encuestas con R </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de encuestas con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimando-contrastes-en-encuestas-de-hogares" class="section level2 hasAnchor" number="4.8">
<h2><span class="header-section-number">4.8</span> Estimando contrastes en encuestas de hogares<a href="estimando-contrastes-en-encuestas-de-hogares.html#estimando-contrastes-en-encuestas-de-hogares" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En muchas ocasiones, en encuestas de hogares se requiere comparar más de dos poblaciones al mismo tiempo, por ejemplo, comparar los ingresos medios de los hogares en 3 regiones o municipalidades en la postpandemia con el fin de verificar y sectorizar aquellas municipalidades o regiones donde más impacto en el desempleo y falta de ingresos tuvo el Covid-19 en los hogares. En casos como estos la diferencia de media que estudiamos en capítulos anteriores se queda corta dado que permite solo comprar parejas de poblaciones y por ende que, hacer contraste resulta una muy buena alternativa para abordar este tipo de problemas.</p>
<p>Recurriendo en las definiciones que se han trabajado en este capítulo, un contraste es una combinación lineal de parámetros de la forma:</p>
<p><span class="math display">\[\begin{eqnarray*}
f\left(\theta_{1},\theta_{2},...,\theta_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}\theta_{j}
\end{eqnarray*}\]</span></p>
<p>Una estimación de esta función está dada por:</p>
<p><span class="math display">\[\begin{eqnarray*}
f\left(\hat{\theta}_{1},\hat{\theta}_{2},...,\hat{\theta}_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}\hat{\theta}_{j}
\end{eqnarray*}\]</span></p>
<p>cuya varianza del estimador se calcula como sigue:</p>
<p><span class="math display">\[\begin{eqnarray*}
var\left(\sum_{j=1}^{J}a_{j}\hat{\theta}_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}^{2}var\left(\hat{\theta}_{j}\right)+2\times\sum_{j=1}^{J-1}\sum_{k&gt;j}^{J}a_{j}a_{k}\,cov\left(\hat{\theta}_{j},\hat{\theta}_{k}\right)
\end{eqnarray*}\]</span></p>
<p>Los procedimientos metodológicos para implementar los contrastes en diseños de muestreo complejos están desarrolladas en la función <code>svycontrast</code>. A continuación, se muestra el uso de dicha función para el cálculo de contraste en la base de datos de ejemplo, comparando el promedio de ingresos por región.</p>
<p>Como primer ejemplo, se realizará la comparación de dos poblaciones, las regiones Norte y Sur (<span class="math inline">\(\bar{Y}_{Norte} - \bar{Y}_{Sur}\)</span>) y luego sí se compararán todas las regiones.</p>
<p>Puesto que esto es un contraste en donde hay 5 regiones y solo se construirá el contraste para la región Norte y la Sur, el contraste queda definido de la siguiente manera:</p>
<p><span class="math display">\[\begin{eqnarray*}
&amp; 1\times\hat{\bar{Y}}_{Norte}+\left(-1\right)\times\hat{\bar{Y}}_{Sur}+0\times\hat{\bar{Y}}_{Centro}+0\times\hat{\bar{Y}}_{Occidente}+0\times\hat{\bar{Y}}_{Oriente}
\end{eqnarray*}\]</span></p>
<p>que de forma matricial queda de la siguiente manera:</p>
<p><span class="math display">\[\begin{eqnarray*}
&amp; \left[1,\,-1,\,0,\,0,\,0\right]\times\left[\begin{array}{c}
\hat{\bar{Y}}_{Norte}\\
\hat{\bar{Y}}_{Sur}\\
\hat{\bar{Y}}_{Centro}\\
\hat{\bar{Y}}_{Occidente}\\
\hat{\bar{Y}}_{Oriente}
\end{array}\right]
\end{eqnarray*}\]</span></p>
<p>Como se puede observar, en este caso el vector de contraste es <span class="math inline">\(\left[1,\,-1,\,0,\,0,\,0\right]\)</span>.</p>
<p>Ahora bien, para realizar el procesos de la construcción del estimador del contraste y su varianza estimada paso a paso se inicia con calcular las medias estimadas por región con la función <code>svyby</code> como se muestra a continuación:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-1" aria-hidden="true" tabindex="-1"></a>prom_region <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Income, </span>
<span id="cb154-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">by =</span> <span class="sc">~</span>Region, </span>
<span id="cb154-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">design =</span> diseno, </span>
<span id="cb154-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">FUN =</span> svymean, </span>
<span id="cb154-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">na.rm=</span>T, </span>
<span id="cb154-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">covmat =</span> <span class="cn">TRUE</span>, </span>
<span id="cb154-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb154-8"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb154-8" aria-hidden="true" tabindex="-1"></a>prom_region</span></code></pre></div>
<pre><code>##              Region   Income       se     ci_l     ci_u
## Norte         Norte 552.3637 55.35987 443.8603 660.8670
## Sur             Sur 625.7740 62.40574 503.4610 748.0870
## Centro       Centro 650.7820 61.46886 530.3053 771.2588
## Occidente Occidente 517.0071 46.22077 426.4161 607.5982
## Oriente     Oriente 541.7543 71.66487 401.2938 682.2149</code></pre>
<p>La función <code>svyby</code> permite aplicar una función, en este caso la media (svymean) por región (by) utilizando el diseño muestral empleado (design). Las demás componentes de la función ya se han utilizado previamente. Como resultado de aplicar esta función se obtienen las medias estimadas de los ingresos por región. Se tomarán solo los ingresos medios estimados de las regiones Norte y Sur y calcularemos su diferencia:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: diferencia de estimaciones (Norte - Sur) </span></span>
<span id="cb156-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb156-2" aria-hidden="true" tabindex="-1"></a><span class="fl">552.4</span> <span class="sc">-</span> <span class="fl">625.8</span></span></code></pre></div>
<pre><code>## [1] -73.4</code></pre>
<p>El paso siguiente es calcular la matriz de varianzas y covarianzas y de allí extraer las varianzas y covarianzas de las regiones Norte y Sur:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Matriz de varianzas y covarianzas</span></span>
<span id="cb158-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb158-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(prom_region)</span></code></pre></div>
<pre><code>##              Norte      Sur  Centro Occidente  Oriente
## Norte     3064.715    0.000    0.00     0.000    0.000
## Sur          0.000 3894.476    0.00     0.000    0.000
## Centro       0.000    0.000 3778.42     0.000    0.000
## Occidente    0.000    0.000    0.00  2136.359    0.000
## Oriente      0.000    0.000    0.00     0.000 5135.854</code></pre>
<p>Para calcular el error estándar de la diferencia (contraste) se usará las propiedades de la varianza como es
<span class="math inline">\(se\left(\hat{\bar{y}}_{Norte}-\hat{\bar{y}}_{Sur}\right)=\sqrt{var\left(\hat{\bar{y}}_{Norte}\right)+var\left(\hat{\bar{y}}_{Sur}\right)-2\,cov\left(\hat{\bar{y}}_{Norte},\hat{\bar{y}}_{Sur}\right)}\)</span> tenemos:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">3065</span> <span class="sc">+</span> <span class="dv">3894</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 83.42062</code></pre>
<p>Finalmente, la función <code>svycontrast</code> nos devuelve el contraste estimado y su error estándar. Los argumentos de esta función son los promedios de los ingresos estimados (stat) y las constantes de contraste (contrasts).</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_region, </span>
<span id="cb162-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb162-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">diff_NS =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb162-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb162-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##          contrast  diff_NS
## diff_NS -73.41034 83.42176</code></pre>
<p>Obteniendo como resultado que los ingresos medios estimados para la región Sur es 73.4 unidades monetarias mayor que los ingresos en la región Norte con un error estándar de 83.42 unidades.</p>
<p>Ahora bien, si el objetivo es estimar los siguientes contrastes:</p>
<ul>
<li><span class="math inline">\(\bar{Y}_{Norte} - \bar{Y}_{Centro}\)</span>,</li>
<li><span class="math inline">\(\bar{Y}_{Sur}-\bar{Y}_{Centro}\)</span><br />
</li>
<li><span class="math inline">\(\bar{Y}_{Occidente}-\bar{Y}_{Oriente}\)</span></li>
</ul>
<p>Que escritas de forma matricial se tiene:</p>
<p><span class="math display">\[
\left[\begin{array}{ccccc}
1 &amp; 0 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 1 &amp; -1
\end{array}\right]
\]</span></p>
<p>Ahora, aplicando la función <code>svycontrast</code> en R se obtiene:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_region, </span>
<span id="cb164-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb164-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb164-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb164-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Norte_sur =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb164-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb164-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Sur_centro =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb164-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb164-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Occidente_Oriente =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span>                               <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##                    contrast       SE
## Norte_sur         -98.41834 82.72324
## Sur_centro        -25.00800 87.59507
## Occidente_Oriente -24.74720 85.27727</code></pre>
<p>De lo cual se puede concluir que, las regiones con los ingresos medios de los hogares más similares son la región sur y la región centro.</p>
<p>También es posible construir contraste en variables que estén correlacionadas. Por ejemplo, Ingreso y Sexo. Como se hizo en el ejemplo anterior, se inicia con el promedio estimado por sexo.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-1" aria-hidden="true" tabindex="-1"></a>prom_sexo <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Income, </span>
<span id="cb166-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">by =</span> <span class="sc">~</span>Sex, </span>
<span id="cb166-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">design =</span> diseno,</span>
<span id="cb166-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">FUN =</span> svymean, </span>
<span id="cb166-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">na.rm=</span>T,</span>
<span id="cb166-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb166-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb166-8"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb166-8" aria-hidden="true" tabindex="-1"></a>prom_sexo</span></code></pre></div>
<pre><code>##           Sex   Income       se     ci_l     ci_u
## Female Female 557.5681 25.82995 506.9423 608.1939
## Male     Male 585.8496 34.58759 518.0592 653.6400</code></pre>
<p>El contraste a estimar es:</p>
<p><span class="math display">\[ \bar{Y}_{F} - \bar{Y}_{M}\]</span>
Por tanto, usando la función <code>svycontrast</code> se obtiene el contraste estimado:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_sexo,</span>
<span id="cb168-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb168-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">diff_Sexo =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb168-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb168-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##            contrast diff_Sexo
## diff_Sexo -28.28149  20.75651</code></pre>
<p>Obteniendo como resultado que, en promedio, los hombres obtienen 28.3 unidades monetarias más que las mujeres con una desviación de 20.76.</p>
<p>Otra posibilidad es poder obtener resultados agregados, por ejemplo:</p>
<p><span class="math inline">\(\hat{\bar{y}}_{Norte}+\hat{\bar{y}}_{Sur} +\hat{\bar{y}}_{Centro}\)</span></p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb170-1" aria-hidden="true" tabindex="-1"></a>sum_region <span class="ot">&lt;-</span> <span class="fu">svyby</span>( <span class="sc">~</span> Income,  <span class="sc">~</span> Region,</span>
<span id="cb170-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb170-2" aria-hidden="true" tabindex="-1"></a>                     diseno, svytotal, <span class="at">na.rm =</span> T,</span>
<span id="cb170-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb170-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb170-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb170-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb170-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb170-5" aria-hidden="true" tabindex="-1"></a>sum_region</span></code></pre></div>
<pre><code>##              Region   Income      se     ci_l     ci_u
## Norte         Norte 14277323 1507575 11322530 17232115
## Sur             Sur 16068151 1877989 12387359 19748942
## Centro       Centro 16483319 2383556 11811634 21155003
## Occidente Occidente 16853540 1823807 13278944 20428135
## Oriente     Oriente 22111335 2833460 16557856 27664814</code></pre>
<p>La matriz de contraste queda como:
<span class="math display">\[
\left[\begin{array}{cccccc}
1 &amp; 1 &amp; 1 &amp; 0 &amp; 0
\end{array}\right]
\]</span>
el procedimiento en R es:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> sum_region,</span>
<span id="cb172-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb172-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb172-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb172-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Agregado_NCS =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span>                        <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##              contrast Agregado_NCS
## Agregado_NCS 46828792      3388357</code></pre>
<p>Por otro lado, si se desean obtener los promedios por categorías. Por ejemplo:</p>
<p><span class="math display">\[
\hat{\bar{y}}_{Edad} = \frac{1}{k}\sum_{k=1}^K\hat{\bar{y}}_{k}
\]</span>
donde <span class="math inline">\(K\)</span> es el número de categorías de la variable. En R se hace de la siguiente manera:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb174-1" aria-hidden="true" tabindex="-1"></a>prom_edad <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Income, </span>
<span id="cb174-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb174-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">by =</span> <span class="sc">~</span>CatAge,</span>
<span id="cb174-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb174-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">design =</span>  diseno, </span>
<span id="cb174-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb174-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">FUN =</span> svymean, </span>
<span id="cb174-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb174-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">na.rm=</span>T,</span>
<span id="cb174-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb174-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">covmat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb174-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb174-7" aria-hidden="true" tabindex="-1"></a>prom_edad</span></code></pre></div>
<pre><code>##              CatAge   Income       se
## 0-5             0-5 463.7715 28.86795
## 6-15           6-15 511.6179 34.88031
## 16-30         16-30 607.2917 37.41561
## 31-45         31-45 573.4167 26.94744
## 46-60         46-60 763.0610 58.97170
## Más de 60 Más de 60 466.6133 31.20795</code></pre>
<p>Cuya matriz de contraste estaría dada por:
<span class="math display">\[
\left[\begin{array}{cccccc}
\frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6}
\end{array}\right]
\]</span></p>
<p>El procedimiento en R es:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_edad, </span>
<span id="cb176-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb176-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb176-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb176-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">agregado_edad =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)))             <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##               contrast agregado_edad
## agregado_edad 564.2954      25.40408</code></pre>
<p>Puesto que los contrastes, como ya se mencionó, es una función lineal de parámetros, se puede también realizar contraste con parámetros tipo razón. Por ejemplo, la relación de gastos contra ingresos por sexo. A continuación, se muestran los códigos computacionales:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-1" aria-hidden="true" tabindex="-1"></a>razon_sexo <span class="ot">&lt;-</span> <span class="fu">svyby</span>( <span class="at">formula =</span> <span class="sc">~</span>Income, </span>
<span id="cb178-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">by =</span> <span class="sc">~</span>Sex,</span>
<span id="cb178-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">denominator =</span> <span class="sc">~</span>Expenditure,</span>
<span id="cb178-4"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">design =</span> diseno, </span>
<span id="cb178-5"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">FUN =</span> svyratio, </span>
<span id="cb178-6"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.rm=</span>T, <span class="at">covmat =</span> <span class="cn">TRUE</span>, </span>
<span id="cb178-7"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb178-8"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb178-8" aria-hidden="true" tabindex="-1"></a>razon_sexo</span></code></pre></div>
<pre><code>##           Sex Income/Expenditure se.Income/Expenditure     ci_l     ci_u
## Female Female           1.519060            0.04582607 1.429243 1.608878
## Male     Male           1.564762            0.07044239 1.426698 1.702827</code></pre>
<p>Cuya estimación de contraste sería:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> razon_sexo, </span>
<span id="cb180-2"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb180-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb180-3"><a href="estimando-contrastes-en-encuestas-de-hogares.html#cb180-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">diff_sexo =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##              contrast  diff_sexo
## diff_sexo -0.04570214 0.04163431</code></pre>
<p>de lo que se puede concluir que la diferencia de las proporciones es 0.045 en favor de los hombres.</p>

</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="estimando-razones-en-encuestas-de-hogares.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/psirusteam/2021ASDA/04-Continuas.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Análisis de encuestas con R.pdf", "Análisis de encuestas con R.epub", "Análisis de encuestas con R.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
