<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.1 Estimación de los parámetros en un modelo de regresión con muestras complejas. | Análisis de encuestas con R</title>
  <meta name="description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="6.1 Estimación de los parámetros en un modelo de regresión con muestras complejas. | Análisis de encuestas con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="github-repo" content="psirusteam/HHS-Handbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.1 Estimación de los parámetros en un modelo de regresión con muestras complejas. | Análisis de encuestas con R" />
  
  <meta name="twitter:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  

<meta name="author" content="Andrés Gutiérrez, Cristian Téllez, Stalyn Guerrero" />


<meta name="date" content="2023-03-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modelos-de-regresión-bajo-diseños-de-muestreo-complejos.html"/>
<link rel="next" href="diagnóstico-del-modelo.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis de encuestas con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="chapter" data-level="1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="conceptos-básicos-en-encuestas-de-hogares.html"><a href="conceptos-básicos-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>2</b> Conceptos básicos en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="universo-de-estudio-y-población-objetivo.html"><a href="universo-de-estudio-y-población-objetivo.html"><i class="fa fa-check"></i><b>2.1</b> Universo de estudio y población objetivo</a></li>
<li class="chapter" data-level="2.2" data-path="unidades-de-análisis.html"><a href="unidades-de-análisis.html"><i class="fa fa-check"></i><b>2.2</b> Unidades de análisis</a></li>
<li class="chapter" data-level="2.3" data-path="unidades-de-muestreo.html"><a href="unidades-de-muestreo.html"><i class="fa fa-check"></i><b>2.3</b> Unidades de muestreo</a></li>
<li class="chapter" data-level="2.4" data-path="marcos-de-muestreo.html"><a href="marcos-de-muestreo.html"><i class="fa fa-check"></i><b>2.4</b> Marcos de muestreo</a></li>
<li class="chapter" data-level="2.5" data-path="selección-de-una-muestra.html"><a href="selección-de-una-muestra.html"><i class="fa fa-check"></i><b>2.5</b> Selección de una muestra</a></li>
<li class="chapter" data-level="2.6" data-path="motivación.html"><a href="motivación.html"><i class="fa fa-check"></i><b>2.6</b> Motivación</a></li>
<li class="chapter" data-level="2.7" data-path="muestreo-aleatorio-simple-en-dos-etapas-estratificado.html"><a href="muestreo-aleatorio-simple-en-dos-etapas-estratificado.html"><i class="fa fa-check"></i><b>2.7</b> Muestreo aleatorio simple en dos etapas estratificado</a></li>
<li class="chapter" data-level="2.8" data-path="práctica-en-r.html"><a href="práctica-en-r.html"><i class="fa fa-check"></i><b>2.8</b> Práctica en <code>R</code></a></li>
<li class="chapter" data-level="2.9" data-path="calibrando-con-r.html"><a href="calibrando-con-r.html"><i class="fa fa-check"></i><b>2.9</b> Calibrando con <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manejando-una-base-de-encuestas-de-hogares-con-r.html"><a href="manejando-una-base-de-encuestas-de-hogares-con-r.html"><i class="fa fa-check"></i><b>3</b> Manejando una base de encuestas de hogares con R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="fundamentos-básicos-de-r-y-rstudio.html"><a href="fundamentos-básicos-de-r-y-rstudio.html"><i class="fa fa-check"></i><b>3.1</b> Fundamentos básicos de R y Rstudio</a></li>
<li class="chapter" data-level="3.2" data-path="algunas-librerías-de-interés.html"><a href="algunas-librerías-de-interés.html"><i class="fa fa-check"></i><b>3.2</b> Algunas librerías de interés</a></li>
<li class="chapter" data-level="3.3" data-path="cración-de-proyectos-en-r.html"><a href="cración-de-proyectos-en-r.html"><i class="fa fa-check"></i><b>3.3</b> Cración de proyectos en <code>R</code></a></li>
<li class="chapter" data-level="3.4" data-path="lectura-de-las-bases-de-datos-y-manipulación.html"><a href="lectura-de-las-bases-de-datos-y-manipulación.html"><i class="fa fa-check"></i><b>3.4</b> Lectura de las bases de datos y manipulación</a></li>
<li class="chapter" data-level="3.5" data-path="el-operador-pipe.html"><a href="el-operador-pipe.html"><i class="fa fa-check"></i><b>3.5</b> El operador <code>pipe</code></a></li>
<li class="chapter" data-level="3.6" data-path="funciones-mutate-summarise-y-group_by-en-encuestas-de-hogares.html"><a href="funciones-mutate-summarise-y-group_by-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>3.6</b> Funciones <strong>mutate, summarise y group_by</strong> en encuestas de hogares</a></li>
<li class="chapter" data-level="3.7" data-path="medidas-descriptivos-y-reflexiones.html"><a href="medidas-descriptivos-y-reflexiones.html"><i class="fa fa-check"></i><b>3.7</b> Medidas descriptivos y reflexiones</a></li>
<li class="chapter" data-level="3.8" data-path="algunas-reflexiones-generales.html"><a href="algunas-reflexiones-generales.html"><i class="fa fa-check"></i><b>3.8</b> Algunas reflexiones generales</a></li>
<li class="chapter" data-level="3.9" data-path="observación-importante.html"><a href="observación-importante.html"><i class="fa fa-check"></i><b>3.9</b> <strong>¡Observación importante!</strong></a></li>
<li class="chapter" data-level="3.10" data-path="medias-y-totales.html"><a href="medias-y-totales.html"><i class="fa fa-check"></i><b>3.10</b> Medias y totales</a></li>
<li class="chapter" data-level="3.11" data-path="medianas-y-percentiles.html"><a href="medianas-y-percentiles.html"><i class="fa fa-check"></i><b>3.11</b> Medianas y percentiles</a></li>
<li class="chapter" data-level="3.12" data-path="varianza-desviación-estándar-y-rangos.html"><a href="varianza-desviación-estándar-y-rangos.html"><i class="fa fa-check"></i><b>3.12</b> Varianza, desviación estándar y rangos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-de-las-variables-continuas-en-encuestas-de-hogares.html"><a href="análisis-de-las-variables-continuas-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4</b> Análisis de las variables continuas en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lectura-de-bases-de-datos-y-definición-del-diseño-muestral.html"><a href="lectura-de-bases-de-datos-y-definición-del-diseño-muestral.html"><i class="fa fa-check"></i><b>4.1</b> Lectura de bases de datos y definición del diseño muestral</a></li>
<li class="chapter" data-level="4.2" data-path="análisis-gráfico-histogramas-y-boxplot.html"><a href="análisis-gráfico-histogramas-y-boxplot.html"><i class="fa fa-check"></i><b>4.2</b> Análisis gráfico: Histogramas y Boxplot</a></li>
<li class="chapter" data-level="4.3" data-path="estimación-puntual.html"><a href="estimación-puntual.html"><i class="fa fa-check"></i><b>4.3</b> Estimación puntual</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-totales-e-intervalos-de-confianza"><i class="fa fa-check"></i><b>4.3.1</b> Estimación de totales e intervalos de confianza</a></li>
<li class="chapter" data-level="4.3.2" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-la-media-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.3.2</b> Estimación de la media e intervalo de confianza</a></li>
<li class="chapter" data-level="4.3.3" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-medidas-de-dispersión-y-localización"><i class="fa fa-check"></i><b>4.3.3</b> Estimación de medidas de dispersión y localización</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="estimación-del-coeficiente-de-ginni-en-encuestas-de-hogares.html"><a href="estimación-del-coeficiente-de-ginni-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.4</b> Estimación del coeficiente de Ginni en encuestas de hogares</a></li>
<li class="chapter" data-level="4.5" data-path="análisis-de-la-relación-entre-dos-variable-continuas.html"><a href="análisis-de-la-relación-entre-dos-variable-continuas.html"><i class="fa fa-check"></i><b>4.5</b> Análisis de la relación entre dos variable continuas</a></li>
<li class="chapter" data-level="4.6" data-path="prueba-de-hipótesis-para-la-diferencia-de-medias-en-encuestas-de-hogares.html"><a href="prueba-de-hipótesis-para-la-diferencia-de-medias-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.6</b> Prueba de hipótesis para la diferencia de medias en encuestas de hogares</a></li>
<li class="chapter" data-level="4.7" data-path="estimando-razones-en-encuestas-de-hogares.html"><a href="estimando-razones-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.7</b> Estimando razones en encuestas de hogares</a></li>
<li class="chapter" data-level="4.8" data-path="estimando-contrastes-en-encuestas-de-hogares.html"><a href="estimando-contrastes-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.8</b> Estimando contrastes en encuestas de hogares</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="análisis-de-variables-categóricas-en-encuestas-de-hogares.html"><a href="análisis-de-variables-categóricas-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>5</b> Análisis de variables categóricas en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estimaciones-de-totales.html"><a href="estimaciones-de-totales.html"><i class="fa fa-check"></i><b>5.1</b> Estimaciones de totales</a></li>
<li class="chapter" data-level="5.2" data-path="estimación-de-proporciones.html"><a href="estimación-de-proporciones.html"><i class="fa fa-check"></i><b>5.2</b> Estimación de proporciones</a></li>
<li class="chapter" data-level="5.3" data-path="tablas-cruzadas..html"><a href="tablas-cruzadas..html"><i class="fa fa-check"></i><b>5.3</b> Tablas cruzadas.</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelos-de-regresión-bajo-diseños-de-muestreo-complejos.html"><a href="modelos-de-regresión-bajo-diseños-de-muestreo-complejos.html"><i class="fa fa-check"></i><b>6</b> Modelos de regresión bajo diseños de muestreo complejos</a>
<ul>
<li class="chapter" data-level="6.1" data-path="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html"><i class="fa fa-check"></i><b>6.1</b> Estimación de los parámetros en un modelo de regresión con muestras complejas.</a></li>
<li class="chapter" data-level="6.2" data-path="diagnóstico-del-modelo.html"><a href="diagnóstico-del-modelo.html"><i class="fa fa-check"></i><b>6.2</b> Diagnóstico del modelo</a></li>
<li class="chapter" data-level="6.3" data-path="inferencia-sobre-los-parámetros-del-modelo.html"><a href="inferencia-sobre-los-parámetros-del-modelo.html"><i class="fa fa-check"></i><b>6.3</b> Inferencia sobre los parámetros del Modelo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="gráficas-en-r.html"><a href="gráficas-en-r.html"><i class="fa fa-check"></i><b>7</b> Gráficas en R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="histogramas-para-graficar-variables-continuas..html"><a href="histogramas-para-graficar-variables-continuas..html"><i class="fa fa-check"></i><b>7.1</b> Histogramas para graficar variables continuas.</a></li>
<li class="chapter" data-level="7.2" data-path="agregando-densidades-y-graficando-boxplot.html"><a href="agregando-densidades-y-graficando-boxplot.html"><i class="fa fa-check"></i><b>7.2</b> Agregando densidades y graficando Boxplot</a></li>
<li class="chapter" data-level="7.3" data-path="scaterplot.html"><a href="scaterplot.html"><i class="fa fa-check"></i><b>7.3</b> Scaterplot</a></li>
<li class="chapter" data-level="7.4" data-path="diagrama-de-barras-para-variables-categoricas.html"><a href="diagrama-de-barras-para-variables-categoricas.html"><i class="fa fa-check"></i><b>7.4</b> Diagrama de barras para variables categoricas</a></li>
<li class="chapter" data-level="7.5" data-path="creando-mapas.html"><a href="creando-mapas.html"><i class="fa fa-check"></i><b>7.5</b> Creando mapas</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelos-lineales-generalizados-en-encuestas-de-hogares.html"><a href="modelos-lineales-generalizados-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>8</b> Modelos lineales generalizados en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="8.1" data-path="prueba-de-independencia-f.html"><a href="prueba-de-independencia-f.html"><i class="fa fa-check"></i><b>8.1</b> Prueba de independencia F</a></li>
<li class="chapter" data-level="8.2" data-path="estadístico-de-wald.html"><a href="estadístico-de-wald.html"><i class="fa fa-check"></i><b>8.2</b> Estadístico de Wald</a></li>
<li class="chapter" data-level="8.3" data-path="modelo-log-lineal-para-tablas-de-contingencia.html"><a href="modelo-log-lineal-para-tablas-de-contingencia.html"><i class="fa fa-check"></i><b>8.3</b> Modelo log lineal para tablas de contingencia</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelos-lineales-generalizados-introducción-a-la-pseudo-máxima-verosimilitud.html"><a href="modelos-lineales-generalizados-introducción-a-la-pseudo-máxima-verosimilitud.html"><i class="fa fa-check"></i><b>9</b> Modelos lineales generalizados: Introducción a la pseudo máxima verosimilitud</a>
<ul>
<li class="chapter" data-level="9.1" data-path="acerca-de-las-muestras-aleatorias-y-su-análisis.html"><a href="acerca-de-las-muestras-aleatorias-y-su-análisis.html"><i class="fa fa-check"></i><b>9.1</b> Acerca de las muestras aleatorias y su análisis</a></li>
<li class="chapter" data-level="9.2" data-path="método-de-máxima-verosimilitud.html"><a href="método-de-máxima-verosimilitud.html"><i class="fa fa-check"></i><b>9.2</b> Método de Máxima Verosimilitud</a></li>
<li class="chapter" data-level="9.3" data-path="método-de-máxima-pseudo-verosimilitud.html"><a href="método-de-máxima-pseudo-verosimilitud.html"><i class="fa fa-check"></i><b>9.3</b> Método de Máxima Pseudo-Verosimilitud</a></li>
<li class="chapter" data-level="9.4" data-path="modelo-multinomial.html"><a href="modelo-multinomial.html"><i class="fa fa-check"></i><b>9.4</b> Modelo multinomial</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="modelos-multinivel-en-el-contexto-de-encuestas-de-hogares.html"><a href="modelos-multinivel-en-el-contexto-de-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>10</b> Modelos multinivel en el contexto de encuestas de hogares</a>
<ul>
<li class="chapter" data-level="10.1" data-path="modelos-multinivel-en-muestras-complejas.html"><a href="modelos-multinivel-en-muestras-complejas.html"><i class="fa fa-check"></i><b>10.1</b> Modelos multinivel en muestras complejas</a></li>
<li class="chapter" data-level="10.2" data-path="estimación-de-pseudo-máxima-verosimilitud.html"><a href="estimación-de-pseudo-máxima-verosimilitud.html"><i class="fa fa-check"></i><b>10.2</b> Estimación de pseudo máxima verosimilitud</a></li>
<li class="chapter" data-level="10.3" data-path="introducción-a-los-modelos-logístico-multinivel..html"><a href="introducción-a-los-modelos-logístico-multinivel..html"><i class="fa fa-check"></i><b>10.3</b> Introducción a los modelos logístico multinivel.</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="imputación-múltiple-en-encuestas-de-hogares.html"><a href="imputación-múltiple-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>11</b> Imputación múltiple en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="11.1" data-path="imputación-por-la-media-no-condicional..html"><a href="imputación-por-la-media-no-condicional..html"><i class="fa fa-check"></i><b>11.1</b> Imputación por la media no condicional.</a></li>
<li class="chapter" data-level="11.2" data-path="imputación-por-la-media-condicional.html"><a href="imputación-por-la-media-condicional.html"><i class="fa fa-check"></i><b>11.2</b> Imputación por la media condicional</a></li>
<li class="chapter" data-level="11.3" data-path="imputación-por-hot-deck-y-cold-deck.html"><a href="imputación-por-hot-deck-y-cold-deck.html"><i class="fa fa-check"></i><b>11.3</b> Imputación por Hot-deck y Cold-deck</a></li>
<li class="chapter" data-level="11.4" data-path="imputación-por-regresión.html"><a href="imputación-por-regresión.html"><i class="fa fa-check"></i><b>11.4</b> Imputación por regresión</a></li>
<li class="chapter" data-level="11.5" data-path="imputación-por-el-vecino-más-cercano.html"><a href="imputación-por-el-vecino-más-cercano.html"><i class="fa fa-check"></i><b>11.5</b> Imputación por el vecino más cercano</a></li>
<li class="chapter" data-level="11.6" data-path="imputación-por-el-vecino-más-cercano-con-regresión.html"><a href="imputación-por-el-vecino-más-cercano-con-regresión.html"><i class="fa fa-check"></i><b>11.6</b> Imputación por el vecino más cercano con regresión</a></li>
<li class="chapter" data-level="11.7" data-path="introducción-a-la-imputación-múltiple..html"><a href="introducción-a-la-imputación-múltiple..html"><i class="fa fa-check"></i><b>11.7</b> Introducción a la imputación múltiple.</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>12</b> Referencias</a></li>
<li class="divider"></li>
<li><a Análisis de encuestas con R </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de encuestas con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas." class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Estimación de los parámetros en un modelo de regresión con muestras complejas.<a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Una vez se establecen los supuestos del modelo y las características distribucionales de los errores el paso siguientes es el proceso de estimación de los parámetros. A modo ilustrativo e introductorio al proceso de estimación de los parámetros con información provenientes de muestras complejas, si en lugar de observar una muestra de tamaño <span class="math inline">\(n\)</span> de los <span class="math inline">\(N\)</span> elementos de población se hubiera realizado un censo completo, el parámetro de regresión de población finita <span class="math inline">\(\beta_{1}\)</span> podría calcularse como sigue <strong>(Tellez, et. al 2016)</strong>:</p>
<p><span class="math display">\[
\beta_{1}  =  \frac{{ \sum_{i=1}^{N}\left(X_{i}-\bar{X}\right)\left(Y_{i}-\bar{Y}\right)}}{\sum_{i=1}^{N}\left(X_{i}-\bar{X}\right)^{2}}
\]</span></p>
<p>Ahora bien, cuando se desea estimar los parámetros de un modelo de regresión lineal, pero considerando que la información muestral proviene de encuestas con muestras complejas se altera el enfoque estándar que se le da a la estimación de coeficientes de regresión y sus errores estándar.</p>
<p>La principal razón por la que los métodos de estimación de parámetros de los coeficientes de regresión cambian es que la información recolectada por medio de una encuesta con muestra compleja generalmente no está distribuida de manera idéntica dado que el diseño muestral así es planeado. En este contexto, al ajustar modelos de regresión con este conjunto de datos, dado que los diseños complejos en su mayoría contienen estratificación, conglomerados, probabilidades de selección desiguales, etc, impiden el uso de estimadores de varianza convencionales que se pueden derivar por máxima verosimilitud puesto que, con esta metodología se asumen que los datos son independientes e idénticamente distribuidos y que provienen de alguna distribución de probabilidad (binomial, Poisson, exponencial, normal, etc.). En su lugar, según <em>Wolter, (2007)</em> se emplean métodos no paramétricos robustos basados en linealización de Taylor o métodos de estimación de la varianza usando replicación (Jackknife, bootstrapping, etc).</p>
<p>Con el fin de ilustrar la forma cómo se estiman los parámetros de regresión del modelo en el contexto de encuestas complejas se realizará estimando el parámetro <span class="math inline">\(\beta_{1}\)</span> y su varianza para una regresión lineal simple. La extensión a la estimación de los parámetros de un modelo de regresión múltiple, algebraicamente es compleja y se sale del contexto de este libro. A continuación, se presenta la estimación del intercepto y su varianza en un modelo de regresión lineal simple:</p>
<p><span class="math display">\[
\hat{\beta_{1}}  =  \frac{{\sum_{h}^{H}\sum_{\alpha}^{a_{h}}\sum_{i=1}^{n_{h\alpha}}\omega_{h\alpha i}\left(y_{h\alpha i}-\bar{y}_{\omega}\right)\left(x_{h\alpha i}-\bar{x}_{\omega}\right)}}{{ \sum_{h}^{H}\sum_{\alpha}^{a_{h}}\sum_{i=1}^{n_{h\alpha}}\omega_{h\alpha i}\left(x_{h\alpha i}-\bar{x}_{\omega}\right)^{2}}}
  = \frac{t_{xy}}{t_{x^{2}}}
\]</span></p>
<p>Como se puede observar en la ecuación anterior, el estimador del parámetro es un cociente de totales, por ende, su varianza estimada está dada por:</p>
<p><span class="math display">\[
var\left(\hat{\beta_{1}}\right)  =  \frac{var\left(t_{xy}\right)+\hat{\beta}_{1}^{2}var\left(t_{x^{2}}\right)-2\hat{\beta}_{1}cov\left(t_{xy},t_{x^{2}}\right)}{\left(t_{x^{2}}\right)^{2}}
\]</span></p>
<p>A modo de generalización según <strong>Kish y Frankel, (1974)</strong> para la estimación de la varianza en un modelo de regresión lineal múltiple los métodos de aproximación requieren totales de muestra ponderados para los cuadrados y productos cruzados de todas las combinaciones <span class="math inline">\(y\)</span> y <span class="math inline">\(x = {1 x_{1} … x_{p}}\)</span>. A continuación, se presenta la estimación:</p>
<p><span class="math display">\[\begin{eqnarray*}
var\left(\hat{\beta}\right)=\hat{\Sigma}\left(\hat{\beta}\right) &amp; = &amp; \left[\begin{array}{cccc}
var\left(\hat{\beta}_{0}\right) &amp; cov\left(\hat{\beta}_{0},\hat{\beta}_{1}\right) &amp; \cdots &amp; cov\left(\hat{\beta}_{0},\hat{\beta}_{p}\right)\\
cov\left(\hat{\beta}_{0},\hat{\beta}_{1}\right) &amp; var\left(\hat{\beta}_{1}\right) &amp; \cdots &amp; cov\left(\hat{\beta}_{1},\hat{\beta}_{p}\right)\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
cov\left(\hat{\beta}_{0},\hat{\beta}_{p}\right) &amp; cov\left(\hat{\beta}_{1},\hat{\beta}_{p}\right) &amp; \cdots &amp; var\left(\hat{\beta}_{p}\right)
\end{array}\right]
\end{eqnarray*}\]</span></p>
<p>Para ejemplificar los conceptos trabajados hasta este momento, se tomará la misma base que se ha venido trabajando durante todo el desarrollo de este libro. Se inicia con el cargue de las librerías, la base de datos y la definición del diseño de muestreo:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">warning =</span> <span class="cn">FALSE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">error =</span> <span class="cn">FALSE</span>)</span>
<span id="cb282-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb282-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tinytex.verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb282-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (survey)</span>
<span id="cb282-5"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb282-6"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(convey)</span>
<span id="cb282-7"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(TeachingSampling)</span>
<span id="cb282-8"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(printr)</span>
<span id="cb282-9"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb282-10"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb282-11"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb282-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code></pre></div>
<p>Cargue de la base y definición del diseño muestral:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(BigCity, <span class="at">package =</span> <span class="st">&quot;TeachingSampling&quot;</span>)</span>
<span id="cb283-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb283-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb283-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb283-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb283-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb283-4" aria-hidden="true" tabindex="-1"></a>encuesta <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;Data/encuesta.rds&quot;</span>)</span>
<span id="cb283-5"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb283-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(encuesta)</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="6%" />
<col width="6%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="6%" />
<col width="5%" />
<col width="4%" />
<col width="4%" />
<col width="2%" />
<col width="6%" />
<col width="4%" />
<col width="8%" />
<col width="7%" />
<col width="5%" />
<col width="2%" />
<col width="2%" />
<col width="4%" />
<col width="4%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">HHID</th>
<th align="left">Stratum</th>
<th align="right">NIh</th>
<th align="right">nIh</th>
<th align="right">dI</th>
<th align="left">PersonID</th>
<th align="left">PSU</th>
<th align="left">Zone</th>
<th align="left">Sex</th>
<th align="right">Age</th>
<th align="left">MaritalST</th>
<th align="right">Income</th>
<th align="right">Expenditure</th>
<th align="left">Employment</th>
<th align="left">Poverty</th>
<th align="right">dki</th>
<th align="right">dk</th>
<th align="right">wk</th>
<th align="left">Region</th>
<th align="left">CatAge</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">idHH00031</td>
<td align="left">idStrt001</td>
<td align="right">9</td>
<td align="right">2</td>
<td align="right">4.5</td>
<td align="left">idPer01</td>
<td align="left">PSU0003</td>
<td align="left">Rural</td>
<td align="left">Male</td>
<td align="right">68</td>
<td align="left">Married</td>
<td align="right">409.9</td>
<td align="right">346.3</td>
<td align="left">Employed</td>
<td align="left">NotPoor</td>
<td align="right">8</td>
<td align="right">36</td>
<td align="right">34.50</td>
<td align="left">Norte</td>
<td align="left">Más de 60</td>
</tr>
<tr class="even">
<td align="left">idHH00031</td>
<td align="left">idStrt001</td>
<td align="right">9</td>
<td align="right">2</td>
<td align="right">4.5</td>
<td align="left">idPer02</td>
<td align="left">PSU0003</td>
<td align="left">Rural</td>
<td align="left">Female</td>
<td align="right">56</td>
<td align="left">Married</td>
<td align="right">409.9</td>
<td align="right">346.3</td>
<td align="left">Employed</td>
<td align="left">NotPoor</td>
<td align="right">8</td>
<td align="right">36</td>
<td align="right">33.64</td>
<td align="left">Norte</td>
<td align="left">46-60</td>
</tr>
<tr class="odd">
<td align="left">idHH00031</td>
<td align="left">idStrt001</td>
<td align="right">9</td>
<td align="right">2</td>
<td align="right">4.5</td>
<td align="left">idPer03</td>
<td align="left">PSU0003</td>
<td align="left">Rural</td>
<td align="left">Female</td>
<td align="right">24</td>
<td align="left">Married</td>
<td align="right">409.9</td>
<td align="right">346.3</td>
<td align="left">Employed</td>
<td align="left">NotPoor</td>
<td align="right">8</td>
<td align="right">36</td>
<td align="right">33.64</td>
<td align="left">Norte</td>
<td align="left">16-30</td>
</tr>
<tr class="even">
<td align="left">idHH00031</td>
<td align="left">idStrt001</td>
<td align="right">9</td>
<td align="right">2</td>
<td align="right">4.5</td>
<td align="left">idPer04</td>
<td align="left">PSU0003</td>
<td align="left">Rural</td>
<td align="left">Male</td>
<td align="right">26</td>
<td align="left">Married</td>
<td align="right">409.9</td>
<td align="right">346.3</td>
<td align="left">Employed</td>
<td align="left">NotPoor</td>
<td align="right">8</td>
<td align="right">36</td>
<td align="right">34.50</td>
<td align="left">Norte</td>
<td align="left">16-30</td>
</tr>
<tr class="odd">
<td align="left">idHH00031</td>
<td align="left">idStrt001</td>
<td align="right">9</td>
<td align="right">2</td>
<td align="right">4.5</td>
<td align="left">idPer05</td>
<td align="left">PSU0003</td>
<td align="left">Rural</td>
<td align="left">Female</td>
<td align="right">3</td>
<td align="left">NA</td>
<td align="right">409.9</td>
<td align="right">346.3</td>
<td align="left">NA</td>
<td align="left">NotPoor</td>
<td align="right">8</td>
<td align="right">36</td>
<td align="right">33.64</td>
<td align="left">Norte</td>
<td align="left">0-5</td>
</tr>
<tr class="even">
<td align="left">idHH00041</td>
<td align="left">idStrt001</td>
<td align="right">9</td>
<td align="right">2</td>
<td align="right">4.5</td>
<td align="left">idPer01</td>
<td align="left">PSU0003</td>
<td align="left">Rural</td>
<td align="left">Female</td>
<td align="right">61</td>
<td align="left">Widowed</td>
<td align="right">823.8</td>
<td align="right">392.2</td>
<td align="left">Employed</td>
<td align="left">NotPoor</td>
<td align="right">8</td>
<td align="right">36</td>
<td align="right">33.64</td>
<td align="left">Norte</td>
<td align="left">Más de 60</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb284-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-2" aria-hidden="true" tabindex="-1"></a>diseno <span class="ot">&lt;-</span> encuesta <span class="sc">%&gt;%</span></span>
<span id="cb284-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb284-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">strata =</span> Stratum,</span>
<span id="cb284-5"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ids =</span> PSU,</span>
<span id="cb284-6"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> wk,</span>
<span id="cb284-7"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">nest =</span> T</span>
<span id="cb284-8"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb284-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>Para efectos de los ejemplos y como se ha hecho en anteriores ocasiones, se divide la muestra en sub-grupos de la encuesta como sigue:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb285-1" aria-hidden="true" tabindex="-1"></a>sub_Urbano <span class="ot">&lt;-</span> diseno <span class="sc">%&gt;%</span>  <span class="fu">filter</span>(Zone <span class="sc">==</span> <span class="st">&quot;Urban&quot;</span>)</span>
<span id="cb285-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb285-2" aria-hidden="true" tabindex="-1"></a>sub_Rural  <span class="ot">&lt;-</span> diseno <span class="sc">%&gt;%</span>  <span class="fu">filter</span>(Zone <span class="sc">==</span> <span class="st">&quot;Rural&quot;</span>)</span>
<span id="cb285-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb285-3" aria-hidden="true" tabindex="-1"></a>sub_Mujer  <span class="ot">&lt;-</span> diseno <span class="sc">%&gt;%</span>  <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">&quot;Female&quot;</span>)</span>
<span id="cb285-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb285-4" aria-hidden="true" tabindex="-1"></a>sub_Hombre <span class="ot">&lt;-</span> diseno <span class="sc">%&gt;%</span>  <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">&quot;Male&quot;</span>)</span></code></pre></div>
<p>En este capítulo se ajustarán los modelos de regresión usando la base de datos de ejemplo que se ha venido trabajando en capítulos anteriores. Puesto que, en modelos de regresión, se utiliza muy frecuente el recurso gráfico. A continuación, se define un tema estándar que la CEPAL tiene para generar sus gráficos el cual se utilizará en este capítulo.</p>
<p>Para observar que existe una correlación entre el ingreso y el gasto, las cuales son las variables que se utilizarán para el ajuste de los modelos, se construye un scatterplot usando la librería <code>ggplot</code>. Cabe resaltar que, como la base de datos encuesta, la cual se usa para ejemplificar es una muestra de la base <code>BigCity</code>, analizaremos de manera gráfica si poblacionalmente las dos variables mencionadas anteriormente tienen correlación como se muestra a continuación:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2); <span class="fu">library</span>(ggpmisc)</span>
<span id="cb286-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-2" aria-hidden="true" tabindex="-1"></a>plot_BigCity <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> BigCity,</span>
<span id="cb286-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">aes</span>(<span class="at">x =</span> Expenditure, <span class="at">y =</span> Income)) <span class="sc">+</span></span>
<span id="cb286-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-4" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb286-5"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb286-6"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">formula =</span> y <span class="sc">~</span> x) <span class="sc">+</span> <span class="fu">theme_cepal</span>()</span>
<span id="cb286-7"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-8"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-8" aria-hidden="true" tabindex="-1"></a>plot_BigCity <span class="sc">+</span> <span class="fu">stat_poly_eq</span>(<span class="at">formula =</span> y<span class="sc">~</span>x, <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(..eq.label..,</span>
<span id="cb286-9"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb286-9" aria-hidden="true" tabindex="-1"></a>   ..rr.label.., <span class="at">sep =</span> <span class="st">&quot;~~~&quot;</span>),<span class="at">size =</span> <span class="dv">3</span>), <span class="at">parse =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="06-Regresi%C3%B3n_files/figure-html/plot1-1.svg" width="672" /></p>
<p>Si bien, existen unas observaciones por fuera de la nube de punto, el comportamiento general de la relación ingresos vs gastos mantiene una tendencia lineal.</p>
<p>Una vez hecho el análisis gráfico de las variables a utilizar en los modelos a trabajar, se realizará primero un ajuste del modelo con los datos poblacionales y con esto poder analizar qué tan bueno serán los ajustes que se realizarán posteriormente. A continuación, se muestra el ajuste del modelo con los datos poblacionales:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb287-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Expenditure, <span class="at">data =</span> BigCity)</span></code></pre></div>
<p>Ahora bien, para observar los parámetros poblacionales del modelo se utilizará la función <code>modelsummary</code> de la librería <code>modelsummary</code> de la siguiente manera:</p>
<table>
<caption><span id="tab:unnamed-chunk-4">Tabla 6.1: </span>Modelo BigCity</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">Pob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="center">123.337</td>
</tr>
<tr class="even">
<td align="left">Expenditure</td>
<td align="center">1.229</td>
</tr>
<tr class="odd">
<td align="left">Num.Obs.</td>
<td align="center">150266</td>
</tr>
<tr class="even">
<td align="left">R2</td>
<td align="center">0.359</td>
</tr>
<tr class="odd">
<td align="left">R2 Adj.</td>
<td align="center">0.359</td>
</tr>
<tr class="even">
<td align="left">RMSE</td>
<td align="center">461.74</td>
</tr>
</tbody>
</table>
<p>De la anterior salida se puede observar que, el intercepto es igual a 123.337 y el parámetro <span class="math inline">\(\beta_{1}\)</span> asociado al gasto es 1.229. La demás información relacionada a esta salida se analizará más adelante.</p>
<p>Una vez revisada la información poblacional, se utilizará la información obtenida de la muestra para estimar los parámetros y con ello analizar qué tan buenas son las estimaciones. A continuación, se presenta una sintaxis similar a la anterior que permite construir el scatterplot pero para los datos de la muestra.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-1" aria-hidden="true" tabindex="-1"></a>plot_sin <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> encuesta,</span>
<span id="cb288-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> Expenditure, <span class="at">y =</span> Income)) <span class="sc">+</span></span>
<span id="cb288-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb288-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb288-5"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">formula =</span> y <span class="sc">~</span> x) <span class="sc">+</span> <span class="fu">theme_cepal</span>()</span>
<span id="cb288-6"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb288-7"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-7" aria-hidden="true" tabindex="-1"></a>plot_sin <span class="sc">+</span> <span class="fu">stat_poly_eq</span>(<span class="at">formula =</span> y<span class="sc">~</span>x, <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(..eq.label..,</span>
<span id="cb288-8"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb288-8" aria-hidden="true" tabindex="-1"></a>     ..rr.label.., <span class="at">sep =</span> <span class="st">&quot;~~~&quot;</span>), <span class="at">size =</span> <span class="dv">5</span>), <span class="at">parse =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="06-Regresi%C3%B3n_files/figure-html/plot2-1.svg" width="672" /></p>
<p>Como se puede observar, los datos de la muestra tienen una tendencia lineal aunque un poco dispersa a medida que crecen los gastos en las familias.</p>
<p>Una vez hecho los análisis gráficos se procede a ajustar los modelos de regresión lineal. A modo de comparar el efecto que tiene hacer un correcto uso de los factores de expansión del diseño, primero, se ajustará un modelo sin tener encuesta dichos factores como se muestra a continuación:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb289-1" aria-hidden="true" tabindex="-1"></a>fit_sinP <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Expenditure, <span class="at">data =</span> encuesta)</span>
<span id="cb289-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb289-2" aria-hidden="true" tabindex="-1"></a>fit_sinP</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Income ~ Expenditure, data = encuesta)
## 
## Coefficients:
## (Intercept)  Expenditure  
##      121.52         1.22</code></pre>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(fit_sinP, <span class="at">header =</span> <span class="cn">FALSE</span>,</span>
<span id="cb291-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb291-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Modelo sin factores de expansion&quot;</span>, </span>
<span id="cb291-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb291-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">&quot;ajps&quot;</span>)</span></code></pre></div>
<pre><code>## 
## \begin{table}[!htbp] \centering 
##   \caption{Modelo sin factores de expansion} 
##   \label{} 
## \begin{tabular}{@{\extracolsep{5pt}}lc} 
## \\[-1.8ex]\hline \\[-1.8ex] 
## \\[-1.8ex] &amp; \textbf{Income} \\ 
## \hline \\[-1.8ex] 
##  Expenditure &amp; 1.220$^{***}$ \\ 
##   &amp; (0.025) \\ 
##   Constant &amp; 121.500$^{***}$ \\ 
##   &amp; (11.410) \\ 
##  N &amp; 2605 \\ 
## R-squared &amp; 0.487 \\ 
## Adj. R-squared &amp; 0.487 \\ 
## Residual Std. Error &amp; 345.000 (df = 2603) \\ 
## F Statistic &amp; 2473.000$^{***}$ (df = 1; 2603) \\ 
## \hline \\[-1.8ex] 
## \multicolumn{2}{l}{$^{***}$p $&lt;$ .01; $^{**}$p $&lt;$ .05; $^{*}$p $&lt;$ .1} \\ 
## \end{tabular} 
## \end{table}</code></pre>
<p>Para el modelo ajustado sin factores de expansión, el <span class="math inline">\(\hat{\beta}_{0}\)</span> es 121.52 y el <span class="math inline">\(\hat{\beta}_{1}\)</span> asociado a la variable gastos es 1.22.</p>
<p>Ahora, haciendo un Scatterplot con los datos encuesta pero utilizando los factores de expansión del diseño se debe agregar <code>mapping = aes(weight = wk)</code> en la función <code>geom_smooth</code>como sigue:</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb293-1" aria-hidden="true" tabindex="-1"></a>plot_Ponde <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> encuesta,</span>
<span id="cb293-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb293-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">aes</span>(<span class="at">x =</span> Expenditure, <span class="at">y =</span> Income)) <span class="sc">+</span> </span>
<span id="cb293-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb293-3" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> wk)) <span class="sc">+</span></span>
<span id="cb293-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb293-4" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">formula =</span> y <span class="sc">~</span> x,                      <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">weight =</span> wk)) <span class="sc">+</span> <span class="fu">theme_cepal</span>()</span>
<span id="cb293-5"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb293-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-6"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb293-6" aria-hidden="true" tabindex="-1"></a>plot_Ponde <span class="sc">+</span> <span class="fu">stat_poly_eq</span>(<span class="at">formula =</span> y<span class="sc">~</span>x, <span class="fu">aes</span>(<span class="at">weight =</span> wk, </span>
<span id="cb293-7"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb293-7" aria-hidden="true" tabindex="-1"></a><span class="at">label =</span> <span class="fu">paste</span>(..eq.label..,..rr.label.., <span class="at">sep =</span> <span class="st">&quot;~~~&quot;</span>)), <span class="at">parse =</span> <span class="cn">TRUE</span>,<span class="at">size =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="06-Regresi%C3%B3n_files/figure-html/plot3-1.svg" width="672" /></p>
<p>En este sentido, para ajustar modelos teniendo en cuenta los factores de expansión existen 2 formas, la primera es usando la función <code>lm</code> y la segunda es usando la función <code>svyglm</code> de la librería <code>survey</code>. A continuación. se ajusta el modelo usando la función <code>lm</code>:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb294-1" aria-hidden="true" tabindex="-1"></a>fit_Ponde <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Expenditure, <span class="at">data =</span> encuesta, <span class="at">weights =</span> wk)</span>
<span id="cb294-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb294-2" aria-hidden="true" tabindex="-1"></a>fit_Ponde</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Income ~ Expenditure, data = encuesta, weights = wk)
## 
## Coefficients:
## (Intercept)  Expenditure  
##      103.14         1.26</code></pre>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb296-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(fit_Ponde, <span class="at">header =</span> <span class="cn">FALSE</span>,</span>
<span id="cb296-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb296-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Modelo encuesta ponderada&quot;</span>, </span>
<span id="cb296-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb296-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">&quot;ajps&quot;</span>)</span></code></pre></div>
<pre><code>## 
## \begin{table}[!htbp] \centering 
##   \caption{Modelo encuesta ponderada} 
##   \label{} 
## \begin{tabular}{@{\extracolsep{5pt}}lc} 
## \\[-1.8ex]\hline \\[-1.8ex] 
## \\[-1.8ex] &amp; \textbf{Income} \\ 
## \hline \\[-1.8ex] 
##  Expenditure &amp; 1.263$^{***}$ \\ 
##   &amp; (0.024) \\ 
##   Constant &amp; 103.100$^{***}$ \\ 
##   &amp; (11.260) \\ 
##  N &amp; 2605 \\ 
## R-squared &amp; 0.509 \\ 
## Adj. R-squared &amp; 0.509 \\ 
## Residual Std. Error &amp; 2627.000 (df = 2603) \\ 
## F Statistic &amp; 2703.000$^{***}$ (df = 1; 2603) \\ 
## \hline \\[-1.8ex] 
## \multicolumn{2}{l}{$^{***}$p $&lt;$ .01; $^{**}$p $&lt;$ .05; $^{*}$p $&lt;$ .1} \\ 
## \end{tabular} 
## \end{table}</code></pre>
<p>Para el modelo ajustado con factores de expansión usando la función <code>lm</code>, el <span class="math inline">\(\hat{\beta}_{0}\)</span> es 103.14 y el <span class="math inline">\(\hat{\beta}_{1}\)</span> asociado a la variable gastos es 1.26. Ahora, haciendo el mismo ajuste pero usando la función <code>svyglm</code>:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb298-1" aria-hidden="true" tabindex="-1"></a>fit_svy <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(Income <span class="sc">~</span> Expenditure, </span>
<span id="cb298-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb298-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">design =</span> diseno, <span class="at">family=</span>stats<span class="sc">::</span><span class="fu">gaussian</span>())</span>
<span id="cb298-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb298-3" aria-hidden="true" tabindex="-1"></a>fit_svy</span></code></pre></div>
<pre><code>## Stratified 1 - level Cluster Sampling design (with replacement)
## With (238) clusters.
## Called via srvyr
## Sampling variables:
##  - ids: PSU
##  - strata: Stratum
##  - weights: wk
## 
## Call:  svyglm(formula = Income ~ Expenditure, design = diseno, family = stats::gaussian())
## 
## Coefficients:
## (Intercept)  Expenditure  
##      103.14         1.26  
## 
## Degrees of Freedom: 2604 Total (i.e. Null);  118 Residual
## Null Deviance:       6.35e+08 
## Residual Deviance: 3.11e+08  AIC: 38300</code></pre>
<p>Obteniendo estimaciones para el <span class="math inline">\(\hat{\beta}_{0}\)</span> es 103.14 y el <span class="math inline">\(\hat{\beta}_{1}\)</span> asociado a la variable gastos es 1.26. Siendo exactamente las mismas que con la función <code>lm</code> ya que, como se definió en los argumentos de la función, la función de enlace es Gausiana.</p>
<p>Por último y a modo de resumen se muestra un gráfico donde se encuentran depositados todos los modelos estimados anteriormente y así poder comparar de manera gráfica su ajuste:</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-1" aria-hidden="true" tabindex="-1"></a>df_model <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb300-2"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">intercept =</span> <span class="fu">c</span>(<span class="fu">coefficients</span>(fit)[<span class="dv">1</span>],</span>
<span id="cb300-3"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-3" aria-hidden="true" tabindex="-1"></a>               <span class="fu">coefficients</span>(fit_sinP)[<span class="dv">1</span>], </span>
<span id="cb300-4"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">coefficients</span>(fit_Ponde)[<span class="dv">1</span>],</span>
<span id="cb300-5"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-5" aria-hidden="true" tabindex="-1"></a>               <span class="fu">coefficients</span>(fit_svy)[<span class="dv">1</span>]), </span>
<span id="cb300-6"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">slope =</span> <span class="fu">c</span>(<span class="fu">coefficients</span>(fit)[<span class="dv">2</span>],</span>
<span id="cb300-7"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-7" aria-hidden="true" tabindex="-1"></a>               <span class="fu">coefficients</span>(fit_sinP)[<span class="dv">2</span>], </span>
<span id="cb300-8"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-8" aria-hidden="true" tabindex="-1"></a>               <span class="fu">coefficients</span>(fit_Ponde)[<span class="dv">2</span>],</span>
<span id="cb300-9"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-9" aria-hidden="true" tabindex="-1"></a>               <span class="fu">coefficients</span>(fit_svy)[<span class="dv">2</span>]),</span>
<span id="cb300-10"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Modelo =</span> <span class="fu">c</span>(<span class="st">&quot;Población&quot;</span>, <span class="st">&quot;Sin ponderar&quot;</span>, </span>
<span id="cb300-11"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-11" aria-hidden="true" tabindex="-1"></a>             <span class="st">&quot;Ponderado(lm)&quot;</span>, <span class="st">&quot;Ponderado(svyglm)&quot;</span>))</span>
<span id="cb300-12"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-12" aria-hidden="true" tabindex="-1"></a>plot_BigCity <span class="sc">+</span>  <span class="fu">geom_abline</span>( <span class="at">data =</span> df_model,</span>
<span id="cb300-13"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>( <span class="at">slope =</span> slope,</span>
<span id="cb300-14"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">intercept =</span> intercept, <span class="at">linetype =</span> Modelo,</span>
<span id="cb300-15"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">color =</span> Modelo ), <span class="at">size =</span> <span class="dv">2</span></span>
<span id="cb300-16"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html#cb300-16" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="06-Regresi%C3%B3n_files/figure-html/plot4-1.svg" width="672" /></p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelos-de-regresión-bajo-diseños-de-muestreo-complejos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diagnóstico-del-modelo.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/psirusteam/2021ASDA/06-Regresión.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Análisis de encuestas con R.pdf", "Análisis de encuestas con R.epub", "Análisis de encuestas con R.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
