<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.2 Estimación de proporciones | Análisis de encuestas con R</title>
  <meta name="description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="5.2 Estimación de proporciones | Análisis de encuestas con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="github-repo" content="psirusteam/2021ASDA" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.2 Estimación de proporciones | Análisis de encuestas con R" />
  
  <meta name="twitter:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  

<meta name="author" content="Andrés Gutiérrez,Stalyn Guerrero, Cristian Téllez, Giovany Babativa" />


<meta name="date" content="2025-09-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tamaño-de-población-y-subpoblaciones-en-encuestas-de-hogares.html"/>
<link rel="next" href="tablas-cruzadas.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis de encuestas con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="chapter" data-level="1" data-path="05-Categóricas.html"><a href="#introducci%C3%B3n"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="05-Categóricas.html"><a href="#conceptos-b%C3%A1sicos-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>2</b> Conceptos básicos en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="05-Categóricas.html"><a href="#universo-de-estudio-y-poblaci%C3%B3n-objetivo"><i class="fa fa-check"></i><b>2.1</b> Universo de estudio y población objetivo</a></li>
<li class="chapter" data-level="2.2" data-path="05-Categóricas.html"><a href="#unidades-de-an%C3%A1lisis"><i class="fa fa-check"></i><b>2.2</b> Unidades de análisis</a></li>
<li class="chapter" data-level="2.3" data-path="unidades-de-muestreo.html"><a href="unidades-de-muestreo.html"><i class="fa fa-check"></i><b>2.3</b> Unidades de muestreo</a></li>
<li class="chapter" data-level="2.4" data-path="marcos-de-muestreo.html"><a href="marcos-de-muestreo.html"><i class="fa fa-check"></i><b>2.4</b> Marcos de muestreo</a></li>
<li class="chapter" data-level="2.5" data-path="05-Categóricas.html"><a href="#motivaci%C3%B3n"><i class="fa fa-check"></i><b>2.5</b> Motivación</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="05-Categóricas.html"><a href="#la-importancia-de-considerar-el-dise%C3%B1o-muestral"><i class="fa fa-check"></i><b>2.5.1</b> La importancia de considerar el diseño muestral</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="05-Categóricas.html"><a href="#par%C3%A1metros-y-estimadores"><i class="fa fa-check"></i><b>2.6</b> Parámetros y Estimadores</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="parámetros-y-estimadores.html"><a href="parámetros-y-estimadores.html"><i class="fa fa-check"></i><b>2.6.1</b> Ajustes Adicionales de los Pesos</a></li>
<li class="chapter" data-level="2.6.2" data-path="parámetros-y-estimadores.html"><a href="parámetros-y-estimadores.html#importancia-de-los-ajustes"><i class="fa fa-check"></i><b>2.6.2</b> Importancia de los Ajustes</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-totales"><i class="fa fa-check"></i><b>2.7</b> Estimación de totales</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="estimación-de-totales.html"><a href="estimación-de-totales.html"><i class="fa fa-check"></i><b>2.7.1</b> Ejemplo ilustrativo</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="05-Categóricas.html"><a href="#efecto-del-dise%C3%B1o-deff"><i class="fa fa-check"></i><b>2.8</b> Efecto del diseño (DEFF)</a></li>
<li class="chapter" data-level="2.9" data-path="muestreo-aleatorio-simple-en-dos-etapas-estratificado.html"><a href="muestreo-aleatorio-simple-en-dos-etapas-estratificado.html"><i class="fa fa-check"></i><b>2.9</b> Muestreo aleatorio simple en dos etapas estratificado</a></li>
<li class="chapter" data-level="2.10" data-path="05-Categóricas.html"><a href="#pr%C3%A1ctica-en-r"><i class="fa fa-check"></i><b>2.10</b> Práctica en <code>R</code></a></li>
<li class="chapter" data-level="2.11" data-path="calibrando-con-r.html"><a href="calibrando-con-r.html"><i class="fa fa-check"></i><b>2.11</b> Calibrando con <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manejando-una-base-de-encuestas-de-hogares-con-r.html"><a href="manejando-una-base-de-encuestas-de-hogares-con-r.html"><i class="fa fa-check"></i><b>3</b> Manejando una base de encuestas de hogares con R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="05-Categóricas.html"><a href="#fundamentos-b%C3%A1sicos-de-r-y-rstudio"><i class="fa fa-check"></i><b>3.1</b> Fundamentos básicos de R y Rstudio</a></li>
<li class="chapter" data-level="3.2" data-path="05-Categóricas.html"><a href="#algunas-librer%C3%ADas-de-inter%C3%A9s"><i class="fa fa-check"></i><b>3.2</b> Algunas librerías de interés</a></li>
<li class="chapter" data-level="3.3" data-path="05-Categóricas.html"><a href="#craci%C3%B3n-de-proyectos-en-r"><i class="fa fa-check"></i><b>3.3</b> Cración de proyectos en <code>R</code></a></li>
<li class="chapter" data-level="3.4" data-path="05-Categóricas.html"><a href="#lectura-de-las-bases-de-datos-y-manipulaci%C3%B3n"><i class="fa fa-check"></i><b>3.4</b> Lectura de las bases de datos y manipulación</a></li>
<li class="chapter" data-level="3.5" data-path="el-operador-pipe.html"><a href="el-operador-pipe.html"><i class="fa fa-check"></i><b>3.5</b> El operador <code>pipe</code></a></li>
<li class="chapter" data-level="3.6" data-path="funciones-mutate-summarise-y-group_by-en-encuestas-de-hogares.html"><a href="funciones-mutate-summarise-y-group_by-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>3.6</b> Funciones <strong>mutate, summarise y group_by</strong> en encuestas de hogares</a></li>
<li class="chapter" data-level="3.7" data-path="medidas-descriptivos-y-reflexiones.html"><a href="medidas-descriptivos-y-reflexiones.html"><i class="fa fa-check"></i><b>3.7</b> Medidas descriptivos y reflexiones</a></li>
<li class="chapter" data-level="3.8" data-path="algunas-reflexiones-generales.html"><a href="algunas-reflexiones-generales.html"><i class="fa fa-check"></i><b>3.8</b> Algunas reflexiones generales</a></li>
<li class="chapter" data-level="3.9" data-path="05-Categóricas.html"><a href="#observaci%C3%B3n-importante"><i class="fa fa-check"></i><b>3.9</b> <strong>¡Observación importante!</strong></a></li>
<li class="chapter" data-level="3.10" data-path="medias-y-totales.html"><a href="medias-y-totales.html"><i class="fa fa-check"></i><b>3.10</b> Medias y totales</a></li>
<li class="chapter" data-level="3.11" data-path="medianas-y-percentiles.html"><a href="medianas-y-percentiles.html"><i class="fa fa-check"></i><b>3.11</b> Medianas y percentiles</a></li>
<li class="chapter" data-level="3.12" data-path="05-Categóricas.html"><a href="#varianza-desviaci%C3%B3n-est%C3%A1ndar-y-rangos"><i class="fa fa-check"></i><b>3.12</b> Varianza, desviación estándar y rangos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="05-Categóricas.html"><a href="#an%C3%A1lisis-de-las-variables-continuas-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>4</b> Análisis de las variables continuas en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="4.1" data-path="05-Categóricas.html"><a href="#lectura-de-bases-de-datos-y-definici%C3%B3n-del-dise%C3%B1o-muestral"><i class="fa fa-check"></i><b>4.1</b> Lectura de bases de datos y definición del diseño muestral</a></li>
<li class="chapter" data-level="4.2" data-path="05-Categóricas.html"><a href="#an%C3%A1lisis-gr%C3%A1fico-histogramas-y-boxplot"><i class="fa fa-check"></i><b>4.2</b> Análisis gráfico: Histogramas y Boxplot</a></li>
<li class="chapter" data-level="4.3" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-totales-medias-y-razones"><i class="fa fa-check"></i><b>4.3</b> Estimación de totales, medias y razones</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-puntual"><i class="fa fa-check"></i><b>4.3.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.3.2" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-totales-e-intervalos-de-confianza"><i class="fa fa-check"></i><b>4.3.2</b> Estimación de totales e intervalos de confianza</a></li>
<li class="chapter" data-level="4.3.3" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-la-media-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.3.3</b> Estimación de la media e intervalo de confianza</a></li>
<li class="chapter" data-level="4.3.4" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-medidas-de-dispersi%C3%B3n-y-localizaci%C3%B3n"><i class="fa fa-check"></i><b>4.3.4</b> Estimación de medidas de dispersión y localización</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-del-coeficiente-de-gini-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>4.4</b> Estimación del coeficiente de Gini en encuestas de hogares</a></li>
<li class="chapter" data-level="4.5" data-path="05-Categóricas.html"><a href="#an%C3%A1lisis-de-correlaci%C3%B3n-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>4.5</b> Análisis de correlación en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="05-Categóricas.html"><a href="#ajuste-al-dise%C3%B1o-muestral"><i class="fa fa-check"></i><b>4.5.1</b> Ajuste al diseño muestral</a></li>
<li class="chapter" data-level="4.5.2" data-path="05-Categóricas.html"><a href="#expresi%C3%B3n-formal"><i class="fa fa-check"></i><b>4.5.2</b> Expresión formal</a></li>
<li class="chapter" data-level="4.5.3" data-path="05-Categóricas.html"><a href="#implementaci%C3%B3n-en-r"><i class="fa fa-check"></i><b>4.5.3</b> Implementación en R</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="05-Categóricas.html"><a href="#an%C3%A1lisis-de-la-relaci%C3%B3n-entre-dos-variable-continuas"><i class="fa fa-check"></i><b>4.6</b> Análisis de la relación entre dos variable continuas</a></li>
<li class="chapter" data-level="4.7" data-path="05-Categóricas.html"><a href="#pruebas-para-la-comparaci%C3%B3n-de-grupos"><i class="fa fa-check"></i><b>4.7</b> Pruebas para la comparación de grupos</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="05-Categóricas.html"><a href="#planteamiento-general-de-hip%C3%B3tesis"><i class="fa fa-check"></i><b>4.7.1</b> Planteamiento general de hipótesis</a></li>
<li class="chapter" data-level="4.7.2" data-path="pruebas-para-la-comparación-de-grupos.html"><a href="pruebas-para-la-comparación-de-grupos.html"><i class="fa fa-check"></i><b>4.7.2</b> Diferencia de medias poblacionales</a></li>
<li class="chapter" data-level="4.7.3" data-path="05-Categóricas.html"><a href="#estad%C3%ADstico-de-prueba-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.7.3</b> Estadístico de prueba e intervalo de confianza</a></li>
<li class="chapter" data-level="4.7.4" data-path="pruebas-para-la-comparación-de-grupos.html"><a href="pruebas-para-la-comparación-de-grupos.html#ejemplo-aplicado-en-r"><i class="fa fa-check"></i><b>4.7.4</b> Ejemplo aplicado en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="estimando-razones-en-encuestas-de-hogares.html"><a href="estimando-razones-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.8</b> Estimando razones en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#implementaci%C3%B3n-computacional-en-r"><i class="fa fa-check"></i>Implementación computacional en <code>R</code></a></li>
<li class="chapter" data-level="" data-path=""><a href="#interpretaci%C3%B3n-aplicada"><i class="fa fa-check"></i>Interpretación aplicada</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="estimando-contrastes-en-encuestas-de-hogares.html"><a href="estimando-contrastes-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>4.9</b> Estimando contrastes en encuestas de hogares</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="05-Categóricas.html"><a href="#an%C3%A1lisis-de-variables-categ%C3%B3ricas-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>5</b> Análisis de variables categóricas en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="5.1" data-path="05-Categóricas.html"><a href="#tama%C3%B1o-de-poblaci%C3%B3n-y-subpoblaciones-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>5.1</b> Tamaño de población y subpoblaciones en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="" data-path="tamaño-de-población-y-subpoblaciones-en-encuestas-de-hogares.html"><a href="tamaño-de-población-y-subpoblaciones-en-encuestas-de-hogares.html"><i class="fa fa-check"></i>Estimaciones de totales en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-proporciones"><i class="fa fa-check"></i><b>5.2</b> Estimación de proporciones</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-proporciones-en-r"><i class="fa fa-check"></i><b>5.2.1</b> Estimación de proporciones en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html"><i class="fa fa-check"></i><b>5.3</b> Tablas cruzadas</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="05-Categóricas.html"><a href="#definici%C3%B3n-y-notaci%C3%B3n"><i class="fa fa-check"></i><b>5.3.1</b> Definición y notación</a></li>
<li class="chapter" data-level="5.3.2" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html#tablas-de-doble-entrada"><i class="fa fa-check"></i><b>5.3.2</b> Tablas de doble entrada</a></li>
<li class="chapter" data-level="5.3.3" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html#extensiones-y-aplicaciones"><i class="fa fa-check"></i><b>5.3.3</b> Extensiones y aplicaciones</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-proporciones-y-tablas-cruzadas"><i class="fa fa-check"></i><b>5.4</b> Estimación de proporciones y tablas cruzadas</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="estimación-de-proporciones-y-tablas-cruzadas.html"><a href="estimación-de-proporciones-y-tablas-cruzadas.html"><i class="fa fa-check"></i><b>5.4.1</b> Proporciones para variables binarias</a></li>
<li class="chapter" data-level="5.4.2" data-path="estimación-de-proporciones-y-tablas-cruzadas.html"><a href="estimación-de-proporciones-y-tablas-cruzadas.html#proporciones-para-variables-multinomiales"><i class="fa fa-check"></i><b>5.4.2</b> Proporciones para variables multinomiales</a></li>
<li class="chapter" data-level="5.4.3" data-path="estimación-de-proporciones-y-tablas-cruzadas.html"><a href="estimación-de-proporciones-y-tablas-cruzadas.html#tablas-cruzadas-o-de-contingencia"><i class="fa fa-check"></i><b>5.4.3</b> Tablas cruzadas o de contingencia</a></li>
<li class="chapter" data-level="5.4.4" data-path="estimación-de-proporciones-y-tablas-cruzadas.html"><a href="estimación-de-proporciones-y-tablas-cruzadas.html#prueba-de-independencia-chi2"><i class="fa fa-check"></i><b>5.4.4</b> Prueba de independencia <span class="math inline">\(\chi^{2}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="05-Categóricas.html"><a href="#modelos-de-regresi%C3%B3n-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>5.5</b> Modelos de regresión en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="05-Categóricas.html"><a href="#antecedentes-hist%C3%B3ricos-y-desarrollos-metodol%C3%B3gicos"><i class="fa fa-check"></i><b>5.5.1</b> Antecedentes históricos y desarrollos metodológicos</a></li>
<li class="chapter" data-level="5.5.2" data-path="05-Categóricas.html"><a href="#relevancia-pr%C3%A1ctica"><i class="fa fa-check"></i><b>5.5.2</b> Relevancia práctica</a></li>
<li class="chapter" data-level="5.5.3" data-path="modelos-de-regresión-en-encuestas-de-hogares.html"><a href="modelos-de-regresión-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>5.5.3</b> ¿Aplicar o no aplicar ponderaciones?</a></li>
<li class="chapter" data-level="5.5.4" data-path="05-Categóricas.html"><a href="#enfoques-inferenciales-para-el-an%C3%A1lisis-de-datos"><i class="fa fa-check"></i><b>5.5.4</b> Enfoques inferenciales para el análisis de datos</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-los-par%C3%A1metros-en-un-modelo-de-regresi%C3%B3n-con-muestras-complejas"><i class="fa fa-check"></i><b>5.6</b> Estimación de los parámetros en un modelo de regresión con muestras complejas</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-par%C3%A1metros"><i class="fa fa-check"></i><b>5.6.1</b> Estimación de parámetros</a></li>
<li class="chapter" data-level="5.6.2" data-path="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas.html"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas.html"><i class="fa fa-check"></i><b>5.6.2</b> Uso de ponderaciones</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="05-Categóricas.html"><a href="#diagn%C3%B3stico-del-modelo"><i class="fa fa-check"></i><b>5.7</b> Diagnóstico del modelo</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="05-Categóricas.html"><a href="#coeficiente-de-determinaci%C3%B3n"><i class="fa fa-check"></i><b>5.7.1</b> Coeficiente de determinación</a></li>
<li class="chapter" data-level="5.7.2" data-path="05-Categóricas.html"><a href="#diagn%C3%B3stico-de-los-residuales"><i class="fa fa-check"></i><b>5.7.2</b> Diagnóstico de los residuales</a></li>
<li class="chapter" data-level="5.7.3" data-path="diagnóstico-del-modelo.html"><a href="diagnóstico-del-modelo.html"><i class="fa fa-check"></i><b>5.7.3</b> Observaciones influyentes</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="05-Categóricas.html"><a href="#inferencia-sobre-los-par%C3%A1metros-del-modelo"><i class="fa fa-check"></i><b>5.8</b> Inferencia sobre los parámetros del modelo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="05-Categóricas.html"><a href="#visualizaci%C3%B3n-de-datos"><i class="fa fa-check"></i><b>6</b> Visualización de datos</a>
<ul>
<li class="chapter" data-level="6.1" data-path="05-Categóricas.html"><a href="#gr%C3%A1ficas-en-r"><i class="fa fa-check"></i><b>6.1</b> Gráficas en <code>R</code></a></li>
<li class="chapter" data-level="6.2" data-path="histogramas-para-graficar-variables-continuas.html"><a href="histogramas-para-graficar-variables-continuas.html"><i class="fa fa-check"></i><b>6.2</b> Histogramas para graficar variables continuas</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="histogramas-para-graficar-variables-continuas.html"><a href="histogramas-para-graficar-variables-continuas.html#histogramas-ponderados-y-no-ponderados"><i class="fa fa-check"></i><b>6.2.1</b> Histogramas ponderados y no ponderados</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="agregando-densidades-y-graficando-boxplot.html"><a href="agregando-densidades-y-graficando-boxplot.html"><i class="fa fa-check"></i><b>6.3</b> Agregando densidades y graficando Boxplot</a></li>
<li class="chapter" data-level="6.4" data-path="05-Categóricas.html"><a href="#diagramas-de-dispersi%C3%B3n-scatterplots"><i class="fa fa-check"></i><b>6.4</b> Diagramas de dispersión (Scatterplots)</a></li>
<li class="chapter" data-level="6.5" data-path="diagrama-de-barras-para-variables-categoricas.html"><a href="diagrama-de-barras-para-variables-categoricas.html"><i class="fa fa-check"></i><b>6.5</b> Diagrama de barras para variables categoricas</a></li>
<li class="chapter" data-level="6.6" data-path="creando-mapas.html"><a href="creando-mapas.html"><i class="fa fa-check"></i><b>6.6</b> Creando mapas</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelos-lineales-generalizados-en-encuestas-de-hogares.html"><a href="modelos-lineales-generalizados-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>7</b> Modelos lineales generalizados en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="7.1" data-path="prueba-de-independencia-f.html"><a href="prueba-de-independencia-f.html"><i class="fa fa-check"></i><b>7.1</b> Prueba de independencia F</a></li>
<li class="chapter" data-level="7.2" data-path="05-Categóricas.html"><a href="#estad%C3%ADstico-de-wald"><i class="fa fa-check"></i><b>7.2</b> Estadístico de Wald</a></li>
<li class="chapter" data-level="7.3" data-path="modelo-log-lineal-para-tablas-de-contingencia.html"><a href="modelo-log-lineal-para-tablas-de-contingencia.html"><i class="fa fa-check"></i><b>7.3</b> Modelo log lineal para tablas de contingencia</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="05-Categóricas.html"><a href="#modelos-lineales-generalizados-introducci%C3%B3n-a-la-pseudo-m%C3%A1xima-verosimilitud"><i class="fa fa-check"></i><b>8</b> Modelos lineales generalizados: Introducción a la pseudo máxima verosimilitud</a>
<ul>
<li class="chapter" data-level="8.1" data-path="05-Categóricas.html"><a href="#acerca-de-las-muestras-aleatorias-y-su-an%C3%A1lisis"><i class="fa fa-check"></i><b>8.1</b> Acerca de las muestras aleatorias y su análisis</a></li>
<li class="chapter" data-level="8.2" data-path="05-Categóricas.html"><a href="#m%C3%A9todo-de-m%C3%A1xima-verosimilitud"><i class="fa fa-check"></i><b>8.2</b> Método de Máxima Verosimilitud</a></li>
<li class="chapter" data-level="8.3" data-path="05-Categóricas.html"><a href="#m%C3%A9todo-de-m%C3%A1xima-pseudo-verosimilitud"><i class="fa fa-check"></i><b>8.3</b> Método de Máxima Pseudo-Verosimilitud</a></li>
<li class="chapter" data-level="8.4" data-path="modelo-multinomial.html"><a href="modelo-multinomial.html"><i class="fa fa-check"></i><b>8.4</b> Modelo multinomial</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelos-multinivel-en-el-contexto-de-encuestas-de-hogares.html"><a href="modelos-multinivel-en-el-contexto-de-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>9</b> Modelos multinivel en el contexto de encuestas de hogares</a>
<ul>
<li class="chapter" data-level="9.1" data-path="modelos-multinivel-en-muestras-complejas.html"><a href="modelos-multinivel-en-muestras-complejas.html"><i class="fa fa-check"></i><b>9.1</b> Modelos multinivel en muestras complejas</a></li>
<li class="chapter" data-level="9.2" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-pseudo-m%C3%A1xima-verosimilitud"><i class="fa fa-check"></i><b>9.2</b> Estimación de pseudo máxima verosimilitud</a></li>
<li class="chapter" data-level="9.3" data-path="05-Categóricas.html"><a href="#introducci%C3%B3n-a-los-modelos-log%C3%ADstico-multinivel."><i class="fa fa-check"></i><b>9.3</b> Introducción a los modelos logístico multinivel.</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-m%C3%BAltiple-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>10</b> Imputación múltiple en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="10.1" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-por-la-media-no-condicional."><i class="fa fa-check"></i><b>10.1</b> Imputación por la media no condicional.</a></li>
<li class="chapter" data-level="10.2" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-por-la-media-condicional"><i class="fa fa-check"></i><b>10.2</b> Imputación por la media condicional</a></li>
<li class="chapter" data-level="10.3" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-por-hot-deck-y-cold-deck"><i class="fa fa-check"></i><b>10.3</b> Imputación por Hot-deck y Cold-deck</a></li>
<li class="chapter" data-level="10.4" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-por-regresi%C3%B3n"><i class="fa fa-check"></i><b>10.4</b> Imputación por regresión</a></li>
<li class="chapter" data-level="10.5" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-por-el-vecino-m%C3%A1s-cercano"><i class="fa fa-check"></i><b>10.5</b> Imputación por el vecino más cercano</a></li>
<li class="chapter" data-level="10.6" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-por-el-vecino-m%C3%A1s-cercano-con-regresi%C3%B3n"><i class="fa fa-check"></i><b>10.6</b> Imputación por el vecino más cercano con regresión</a></li>
<li class="chapter" data-level="10.7" data-path="05-Categóricas.html"><a href="#introducci%C3%B3n-a-la-imputaci%C3%B3n-m%C3%BAltiple."><i class="fa fa-check"></i><b>10.7</b> Introducción a la imputación múltiple.</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>11</b> Referencias</a></li>
<li class="divider"></li>
<li><a Análisis de encuestas con R </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de encuestas con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimación-de-proporciones" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Estimación de proporciones<a href="#estimaci%C3%B3n-de-proporciones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En las encuestas de hogares, <strong>las proporciones</strong> permiten expresar el peso relativo que tienen determinados grupos dentro de la población. Por ejemplo, conocer el porcentaje de hogares que se encuentran por debajo de la línea de pobreza es esencial para evaluar desigualdades socioeconómicas. Para obtener este indicador, se calcula el promedio ponderado de una variable dicotómica, lo que asegura que la estimación represente adecuadamente la distribución poblacional.</p>
<p>De acuerdo con Heeringa, West y Berglund (2017), al transformar las categorías de respuesta originales en variables indicadoras <span class="math inline">\(y\)</span> con valores de 1 y 0 (por ejemplo, 1 = Sí y 0 = No), la proporción estimada se obtiene mediante:</p>
<p><span class="math display">\[\hat{p}_d = \frac{\hat{N}_d}{\hat{N}} = \frac{\displaystyle\sum_{h=1}^{H} \sum_{i \in s_{1h}} \sum_{k \in s_{hi}} w_{hik} I(y_{hik}=d)} {\displaystyle\sum_{h=1}^{H} \sum_{i \in s_{1h}} \sum_{k \in s_{hi}} w_{hik}}\]</span></p>
<p>Dado que se trata de un estimador no lineal, su varianza puede aproximarse mediante la <strong>técnica de linealización de Taylor</strong>, utilizando como función de estimación <span class="math inline">\(z_{hik}=I(y_{hik}=d)-\hat{p}_d\)</span>. Actualmente, la mayoría de los programas estadísticos generan estas proporciones junto con sus errores estándar, generalmente presentados en forma de porcentajes.</p>
<p>En situaciones donde las proporciones se aproximan a 0 o 1, puede ser necesario aumentar el tamaño de la muestra para garantizar resultados sólidos. También es recomendable aplicar métodos que aseguren que los intervalos de confianza permanezcan dentro del rango [0,1], ya que los intervalos convencionales basados en la normal pueden desbordar estos límites y perder su utilidad interpretativa. Una alternativa es la <strong>transformación logit</strong> de la proporción estimada:</p>
<p><span class="math display">\[CI(\hat{p}_d; 1-\alpha) = \frac{\exp \left[\ln\left(\frac{\hat{p}_d}{1-\hat{p}_d}\right) \pm \frac{me(\hat{p}_d)}{\hat{p}_d(1-\hat{p}_d)}\right]}{1 + \exp \left[\ln\left(\frac{\hat{p}_d}{1-\hat{p}_d}\right) \pm \frac{me(\hat{p}_d)}{\hat{p}_d(1-\hat{p}_d)}\right]}\]</span></p>
<p>donde <span class="math inline">\(me(\hat{p}_d) = t_{1-\alpha/2, df} \times se(\hat{p}_d)\)</span>, siendo <span class="math inline">\(t_{1-\alpha/2, df}\)</span> el cuantil de la distribución t de Student con <span class="math inline">\(df = n - H\)</span> grados de libertad, dejando un área <span class="math inline">\(\alpha/2\)</span> a su derecha. Este procedimiento asegura resultados interpretables incluso para proporciones extremas (0 o 1).</p>
<div id="estimación-de-proporciones-en-r" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Estimación de proporciones en <code>R</code><a href="#estimaci%C3%B3n-de-proporciones-en-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Otro parámetro de interés en las encuestas de hogares, particularmente con variables categóricas, es la estimación de <strong>proporciones poblacionales</strong> y sus errores estándar. En términos de notación, la estimación de proporciones de población se define como <span class="math inline">\(p\)</span> y las proporciones muestrales como <span class="math inline">\(\pi\)</span>. Es común que muchos paquetes estadísticos generen estas estimaciones en <strong>escala de porcentaje</strong>, mientras que <code>R</code> las produce en la escala [0,1].</p>
<p>A continuación, se muestra cómo estimar la proporción de personas por <strong>zona</strong> usando <code>srvyr</code> y el diseño muestral previamente definido:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="estimación-de-proporciones.html#cb196-1" tabindex="-1"></a>prop_zona <span class="ot">&lt;-</span> diseno <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Zone) <span class="sc">%&gt;%</span> </span>
<span id="cb196-2"><a href="estimación-de-proporciones.html#cb196-2" tabindex="-1"></a>             <span class="fu">summarise</span>(</span>
<span id="cb196-3"><a href="estimación-de-proporciones.html#cb196-3" tabindex="-1"></a>               <span class="at">prop =</span> <span class="fu">survey_mean</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), </span>
<span id="cb196-4"><a href="estimación-de-proporciones.html#cb196-4" tabindex="-1"></a>                                  <span class="at">proportion =</span> <span class="cn">TRUE</span>))</span>
<span id="cb196-5"><a href="estimación-de-proporciones.html#cb196-5" tabindex="-1"></a>prop_zona</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   Zone   prop prop_se prop_low prop_upp
##   &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Rural 0.480  0.0140    0.452    0.508
## 2 Urban 0.520  0.0140    0.492    0.548</code></pre>
<p>En este ejemplo, la función <code>survey_mean</code> calcula la proporción y, con el parámetro <code>proportion = TRUE</code>, se indica que se desea estimar una <strong>proporción poblacional</strong>. Los resultados muestran que aproximadamente el 47.9% de las personas viven en zona rural (IC 95%: 45.2% - 50.7%) y el 52% en zona urbana (IC 95%: 49.2% - 54.7%).</p>
<p>La librería <code>survey</code> también cuenta con la función <code>survey_prop</code>, diseñada específicamente para estimar proporciones, generando resultados equivalentes:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="estimación-de-proporciones.html#cb198-1" tabindex="-1"></a>prop_zona2 <span class="ot">&lt;-</span> diseno <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Zone) <span class="sc">%&gt;%</span> </span>
<span id="cb198-2"><a href="estimación-de-proporciones.html#cb198-2" tabindex="-1"></a>               <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>)))</span>
<span id="cb198-3"><a href="estimación-de-proporciones.html#cb198-3" tabindex="-1"></a>prop_zona2</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   Zone   prop prop_se prop_low prop_upp
##   &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Rural 0.480  0.0140    0.452    0.508
## 2 Urban 0.520  0.0140    0.492    0.548</code></pre>
<p>El lector puede elegir la función que le resulte más cómoda, ya que ambas permiten obtener estimaciones precisas y sus intervalos de confianza, facilitando la interpretación de los resultados para variables categóricas.</p>
<p>Si el interés ahora se centra en estimar subpoblaciones por ejemplo, proporción de hombres y mujeres que viven en la zona urbana, el código computacional es:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="estimación-de-proporciones.html#cb200-1" tabindex="-1"></a>prop_sexoU <span class="ot">&lt;-</span> sub_Urbano <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Sex) <span class="sc">%&gt;%</span> </span>
<span id="cb200-2"><a href="estimación-de-proporciones.html#cb200-2" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>)))</span>
<span id="cb200-3"><a href="estimación-de-proporciones.html#cb200-3" tabindex="-1"></a>prop_sexoU</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   Sex     prop prop_se prop_low prop_upp
##   &lt;chr&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Female 0.537  0.0130    0.511    0.563
## 2 Male   0.463  0.0130    0.437    0.489</code></pre>
<p>Arrojando como resultado que, el 53.6% de las mujeres y 46.4% de los hombres viven en la zona urbana y con intervalos de confianza (51%, 56.2%) y (43.7%, 48.9%) respectivamente. Los intervalos anteriores nos reflejan que, con una confianza del 95% la cantidad estimada de mujeres que viven en la zona urbana es de56% y de hombres es de 48%.</p>
<p>Realizando el mismo ejercicio anterior, pero ahora en la zona rural se tiene:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="estimación-de-proporciones.html#cb202-1" tabindex="-1"></a>prop_sexoR <span class="ot">&lt;-</span> sub_Rural <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Sex) <span class="sc">%&gt;%</span> </span>
<span id="cb202-2"><a href="estimación-de-proporciones.html#cb202-2" tabindex="-1"></a>              <span class="fu">summarise</span>( <span class="at">n =</span> <span class="fu">unweighted</span>(<span class="fu">n</span>()),</span>
<span id="cb202-3"><a href="estimación-de-proporciones.html#cb202-3" tabindex="-1"></a>                         <span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>)))</span>
<span id="cb202-4"><a href="estimación-de-proporciones.html#cb202-4" tabindex="-1"></a>prop_sexoR</span></code></pre></div>
<pre><code>## # A tibble: 2 × 6
##   Sex        n  prop prop_se prop_low prop_upp
##   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Female   679 0.516 0.00824    0.500    0.533
## 2 Male     618 0.484 0.00824    0.467    0.500</code></pre>
<p>el 51.6% de las mujeres y el 48.4% de los hombres viven en la zona rural con intervalos de confianza de (49.9%, 53.2%) y (46,7%, 50%) respectivamente. Los intervalos de confianza anteriores nos reflejan que, inclusive, con una confianza del 95%, la cantidad estimada de mujeres en la zona rural es de 53% y de hombres es de 50%.</p>
<p>Ahora bien, si nos centramos solo en la población de hombres en la base de datos y se desea estimar la proporción de hombres por zona, el código computacional es el siguiente:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="estimación-de-proporciones.html#cb204-1" tabindex="-1"></a>prop_ZonaH <span class="ot">&lt;-</span> sub_Hombre <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Zone) <span class="sc">%&gt;%</span> </span>
<span id="cb204-2"><a href="estimación-de-proporciones.html#cb204-2" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>)))</span>
<span id="cb204-3"><a href="estimación-de-proporciones.html#cb204-3" tabindex="-1"></a>prop_ZonaH</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   Zone   prop prop_se prop_low prop_upp
##   &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Rural 0.491  0.0178    0.455    0.526
## 2 Urban 0.509  0.0178    0.474    0.545</code></pre>
<p>En la anterior tabla se puede observar que el 49% de los hombres están en la zona rural y el 51% en la zona urbana. Si se observa el intervalo de confianza se puede concluir que, con una confianza del 95%, la población estimada de hombres que viven en la zona rural puede llegar a ser el 52% y en urbana un 54%.</p>
<p>Si se realiza ahora el mismo ejercicio para la mujeres el código computacional es:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="estimación-de-proporciones.html#cb206-1" tabindex="-1"></a>prop_ZonaM <span class="ot">&lt;-</span> sub_Mujer <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Zone) <span class="sc">%&gt;%</span> </span>
<span id="cb206-2"><a href="estimación-de-proporciones.html#cb206-2" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>)))</span>
<span id="cb206-3"><a href="estimación-de-proporciones.html#cb206-3" tabindex="-1"></a>prop_ZonaM</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   Zone   prop prop_se prop_low prop_upp
##   &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Rural 0.470  0.0140    0.443    0.498
## 2 Urban 0.530  0.0140    0.502    0.557</code></pre>
<p>De la tabla anterior se puede inferir que, el 47% de las mujeres están en la zona rural y el 52% en la zona urbana. Observando también intervalos de confianza al 95% de (44%, 49%) y (50%, 55%) para las zonas rural y urbana respectivamente.</p>
<p>Si se desea estimar por varios niveles de desagregación, con el uso de la función <code>group_by</code> es posible estimar un mayor número de niveles de agregación al combinar dos o más variables. Por ejemplo, si se desea estimar la proporción de hombres por zona y en estado de pobreza, se realiza de la siguiente manera:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="estimación-de-proporciones.html#cb208-1" tabindex="-1"></a>prop_ZonaH_Pobreza <span class="ot">&lt;-</span> sub_Hombre <span class="sc">%&gt;%</span></span>
<span id="cb208-2"><a href="estimación-de-proporciones.html#cb208-2" tabindex="-1"></a>                      <span class="fu">group_by</span>(Zone, Poverty) <span class="sc">%&gt;%</span> </span>
<span id="cb208-3"><a href="estimación-de-proporciones.html#cb208-3" tabindex="-1"></a>                      <span class="fu">summarise</span>(</span>
<span id="cb208-4"><a href="estimación-de-proporciones.html#cb208-4" tabindex="-1"></a>                      <span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>)))<span class="sc">%&gt;%</span></span>
<span id="cb208-5"><a href="estimación-de-proporciones.html#cb208-5" tabindex="-1"></a>                      <span class="fu">data.frame</span>()</span>
<span id="cb208-6"><a href="estimación-de-proporciones.html#cb208-6" tabindex="-1"></a>prop_ZonaH_Pobreza</span></code></pre></div>
<pre><code>##    Zone  Poverty      prop    prop_se   prop_low  prop_upp
## 1 Rural  NotPoor 0.5488453 0.06264753 0.42434340 0.6675180
## 2 Rural  Extreme 0.1975254 0.06745258 0.09582905 0.3637294
## 3 Rural Relative 0.2536293 0.03724070 0.18711180 0.3340755
## 4 Urban  NotPoor 0.6599255 0.03662268 0.58415144 0.7283141
## 5 Urban  Extreme 0.1128564 0.02451869 0.07264146 0.1712240
## 6 Urban Relative 0.2272181 0.02604053 0.17979436 0.2828371</code></pre>
<p>De la salida anterior se puede observar que, en la ruralidad, el 19% de los hombres están en pobreza extrema mientras que en la zona urbana el 11% también están en pobreza extrema. Por otro lado, el 54% de los hombres que viven en la zona rural no están en pobreza mientras que, en la zona urbana el 65% no está en esta condición.</p>
<p>El mismo ejercicio anterior para la población de mujeres sería:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="estimación-de-proporciones.html#cb210-1" tabindex="-1"></a>prop_ZonaM_Pobreza <span class="ot">&lt;-</span> sub_Mujer <span class="sc">%&gt;%</span> </span>
<span id="cb210-2"><a href="estimación-de-proporciones.html#cb210-2" tabindex="-1"></a>                      <span class="fu">group_by</span>(Zone, Poverty) <span class="sc">%&gt;%</span> </span>
<span id="cb210-3"><a href="estimación-de-proporciones.html#cb210-3" tabindex="-1"></a>                      <span class="fu">summarise</span>( <span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb210-4"><a href="estimación-de-proporciones.html#cb210-4" tabindex="-1"></a>                      <span class="fu">data.frame</span>()</span>
<span id="cb210-5"><a href="estimación-de-proporciones.html#cb210-5" tabindex="-1"></a>prop_ZonaM_Pobreza</span></code></pre></div>
<pre><code>##    Zone  Poverty      prop    prop_se   prop_low  prop_upp
## 1 Rural  NotPoor 0.5539176 0.05568825 0.44281376 0.6598834
## 2 Rural  Extreme 0.1599702 0.05574533 0.07728197 0.3021593
## 3 Rural Relative 0.2861122 0.04357612 0.20803909 0.3794466
## 4 Urban  NotPoor 0.6612172 0.03224726 0.59475977 0.7218725
## 5 Urban  Extreme 0.1093753 0.02209821 0.07267359 0.1613865
## 6 Urban Relative 0.2294075 0.02655874 0.18106582 0.2861459</code></pre>
<p>De la salida anterior se puede observar que, en la ruralidad, el 16% de las mujeres están en pobreza extrema mientras que en la zona urbana el 10% también están en pobreza extrema. Por otro lado, el 55% de las mujeres que viven en la zona rural no están en pobreza mientras que, en la zona urbana el 66% no está en esta condición.</p>
<p>Si lo que se desea ahora es estimar la proporción de hombres empleados o no por zona, se realiza de la siguiente manera:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="estimación-de-proporciones.html#cb212-1" tabindex="-1"></a>prop_ZonaH_Ocupacion <span class="ot">&lt;-</span> sub_Hombre <span class="sc">%&gt;%</span></span>
<span id="cb212-2"><a href="estimación-de-proporciones.html#cb212-2" tabindex="-1"></a>                        <span class="fu">group_by</span>(Zone, Employment) <span class="sc">%&gt;%</span> </span>
<span id="cb212-3"><a href="estimación-de-proporciones.html#cb212-3" tabindex="-1"></a>                        <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>)))<span class="sc">%&gt;%</span></span>
<span id="cb212-4"><a href="estimación-de-proporciones.html#cb212-4" tabindex="-1"></a>                        <span class="fu">data.frame</span>()</span>
<span id="cb212-5"><a href="estimación-de-proporciones.html#cb212-5" tabindex="-1"></a>prop_ZonaH_Ocupacion</span></code></pre></div>
<pre><code>##    Zone Employment       prop     prop_se   prop_low   prop_upp
## 1 Rural Unemployed 0.05125186 0.015733138 0.02767737 0.09298588
## 2 Rural   Inactive 0.10351629 0.020267044 0.06970747 0.15106011
## 3 Rural   Employed 0.52251375 0.026522751 0.46994089 0.57459249
## 4 Rural       &lt;NA&gt; 0.32271810 0.034987840 0.25763953 0.39547790
## 5 Urban Unemployed 0.04374724 0.008492664 0.02969659 0.06400729
## 6 Urban   Inactive 0.16331307 0.018093938 0.13056379 0.20236490
## 7 Urban   Employed 0.51337023 0.023637331 0.46658553 0.55992181
## 8 Urban       &lt;NA&gt; 0.27956945 0.022085422 0.23799131 0.32531045</code></pre>
<p>De la salida anterior se puede observar que, el 5% de los hombres que viven en la ruralidad están desempleados mientras que el 4% de los que viven en la zona urbana están en esta misma condición. Ahora bien, el 52% de los hombres que viven en la ruralidad trabajan mientras que el 51% de los que viven en la zona rural también están empleados.</p>
<p>Si se hace este mismo ejercicio para las mujeres se obtiene:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="estimación-de-proporciones.html#cb214-1" tabindex="-1"></a>prop_ZonaM_Ocupacion <span class="ot">&lt;-</span> sub_Mujer <span class="sc">%&gt;%</span> </span>
<span id="cb214-2"><a href="estimación-de-proporciones.html#cb214-2" tabindex="-1"></a>                        <span class="fu">group_by</span>(Zone, Employment) <span class="sc">%&gt;%</span> </span>
<span id="cb214-3"><a href="estimación-de-proporciones.html#cb214-3" tabindex="-1"></a>                        <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb214-4"><a href="estimación-de-proporciones.html#cb214-4" tabindex="-1"></a>                        <span class="fu">data.frame</span>()</span>
<span id="cb214-5"><a href="estimación-de-proporciones.html#cb214-5" tabindex="-1"></a>prop_ZonaM_Ocupacion</span></code></pre></div>
<pre><code>##    Zone Employment       prop     prop_se    prop_low   prop_upp
## 1 Rural Unemployed 0.01017065 0.005540256 0.003443802 0.02964628
## 2 Rural   Inactive 0.44719272 0.035247218 0.378871481 0.51756811
## 3 Rural   Employed 0.23999716 0.039151859 0.171118101 0.32570701
## 4 Rural       &lt;NA&gt; 0.30263948 0.030765644 0.245379430 0.36676711
## 5 Urban Unemployed 0.02109678 0.005964137 0.012019202 0.03677508
## 6 Urban   Inactive 0.36445938 0.021442387 0.323143427 0.40787461
## 7 Urban   Employed 0.38455672 0.019452094 0.346831628 0.42372325
## 8 Urban       &lt;NA&gt; 0.22988711 0.013850398 0.203613820 0.25845036</code></pre>
<p>Para las mujeres se puede observar que, el 1% de las mujeres que viven en la ruralidad están desempleados mientras que el 2% de las que viven en la zona urbana están en esta misma condición. Ahora bien, el 24% de las mujeres que viven en la ruralidad trabajan mientras que el 38% de las que viven en la zona rural también están empleados.</p>
<p>Otro parámetro que es de interés es estimar en encuestas de hogares la cantidad de personas menores y mayores de edad en los hogares. A continuación, ejemplificamos la estimación de menores y mayores a 18 años cruzado por pobreza:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="estimación-de-proporciones.html#cb216-1" tabindex="-1"></a>diseno <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(edad_18, pobreza) <span class="sc">%&gt;%</span> </span>
<span id="cb216-2"><a href="estimación-de-proporciones.html#cb216-2" tabindex="-1"></a>           <span class="fu">summarise</span>(<span class="at">Prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb216-3"><a href="estimación-de-proporciones.html#cb216-3" tabindex="-1"></a>           <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##       edad_18 pobreza      Prop    Prop_se  Prop_low  Prop_upp
## 1  &lt; 18 anios       0 0.4984504 0.03729355 0.4251710 0.5717964
## 2  &lt; 18 anios       1 0.5015496 0.03729355 0.4282036 0.5748290
## 3 &gt;= 18 anios       0 0.6646140 0.02978353 0.6033275 0.7208132
## 4 &gt;= 18 anios       1 0.3353860 0.02978353 0.2791868 0.3966725</code></pre>
<p>De la anterior salida se puede observar que, el 50% de los menores de edad y el 33% de los mayores de edad están en estado de pobreza. Al observar los intervalos de confianza para los menores de edad en estado de pobreza se puede observar que, dicha estimación puede llegar, con una confianza del 95% a 57% mientras que a los mayores de edad puede llegar a 39%.</p>
<p>Ahora, si se hace este mismo ejercicio, pero esta vez cruzando con la variable que indica empleo se obtiene:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="estimación-de-proporciones.html#cb218-1" tabindex="-1"></a>diseno <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(edad_18, desempleo) <span class="sc">%&gt;%</span> </span>
<span id="cb218-2"><a href="estimación-de-proporciones.html#cb218-2" tabindex="-1"></a>           <span class="fu">summarise</span>(<span class="at">Prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb218-3"><a href="estimación-de-proporciones.html#cb218-3" tabindex="-1"></a>           <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##       edad_18 desempleo        Prop     Prop_se    Prop_low   Prop_upp
## 1  &lt; 18 anios         0 0.166704172 0.014856561 0.139321648 0.19822898
## 2  &lt; 18 anios         1 0.003729693 0.001969183 0.001309174 0.01057808
## 3  &lt; 18 anios        NA 0.829566135 0.015009188 0.797760089 0.85726505
## 4 &gt;= 18 anios         0 0.955234872 0.007552778 0.937660285 0.96802386
## 5 &gt;= 18 anios         1 0.044765128 0.007552778 0.031976144 0.06233972</code></pre>
<p>De la tabla anterior se puede observar que, el 0.3% de los menores de edad y el 4% de los mayores de edad están desempleados. Adicionalmente, con una confianza del 95% y basados en la muestra se puede observar que el desempleo en menores de edad puede llegar a 0.7% y para los mayores llega a un 5%.</p>
<p>Por otro lado, si el objetivo ahora es estimar la cantidad de menores de edad en la zona rural se realiza de la siguiente manera:</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="estimación-de-proporciones.html#cb220-1" tabindex="-1"></a>sub_Rural <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(edad_18) <span class="sc">%&gt;%</span> </span>
<span id="cb220-2"><a href="estimación-de-proporciones.html#cb220-2" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">Prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb220-3"><a href="estimación-de-proporciones.html#cb220-3" tabindex="-1"></a>              <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##       edad_18      Prop    Prop_se  Prop_low  Prop_upp
## 1  &lt; 18 anios 0.3711613 0.03021982 0.3128746 0.4334566
## 2 &gt;= 18 anios 0.6288387 0.03021982 0.5665434 0.6871254</code></pre>
<p>De la anterior tabla se puede observar que, el 37% de las personas que viven en la zona rural de la base de ejemplo son menores de edad con un intervalo de confianza al 95% comprendido entre 31% y 43%.</p>
<p>Como se mencionó al inicio del capítulo, es posible categorizar una variable de tipo cuantitativo como por ejemplo la edad y cruzarla con la variable que categoriza la empleabilidad. A continuación, se estima la edad de las mujeres por rango.</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="estimación-de-proporciones.html#cb222-1" tabindex="-1"></a>sub_Mujer <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">edad_rango =</span> <span class="fu">case_when</span>(</span>
<span id="cb222-2"><a href="estimación-de-proporciones.html#cb222-2" tabindex="-1"></a>                     Age<span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">35</span>  <span class="sc">~</span> <span class="st">&quot;18 - 35&quot;</span>, <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;Otro&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb222-3"><a href="estimación-de-proporciones.html#cb222-3" tabindex="-1"></a>                     <span class="fu">group_by</span>(edad_rango, Employment) <span class="sc">%&gt;%</span> </span>
<span id="cb222-4"><a href="estimación-de-proporciones.html#cb222-4" tabindex="-1"></a>                     <span class="fu">summarise</span>(<span class="at">Prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb222-5"><a href="estimación-de-proporciones.html#cb222-5" tabindex="-1"></a>                     <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##   edad_rango Employment       Prop     Prop_se    Prop_low   Prop_upp
## 1    18 - 35 Unemployed 0.02893412 0.009142347 0.015403014 0.05370358
## 2    18 - 35   Inactive 0.51653851 0.037905184 0.441673039 0.59066889
## 3    18 - 35   Employed 0.45452737 0.035685710 0.385232560 0.52562948
## 4       Otro Unemployed 0.01015164 0.004026104 0.004617517 0.02217073
## 5       Otro   Inactive 0.35271022 0.020725430 0.312834830 0.39474850
## 6       Otro   Employed 0.25483870 0.021700305 0.214292062 0.30012671
## 7       Otro       &lt;NA&gt; 0.38229944 0.022313379 0.339191706 0.42734277</code></pre>
<p>De la anterior tabla se puede observar, entre otros que, las mujeres con edades entre 18 y 35 años el 2% están desempleadas y el 45% están empleadas. Análisis similares se pueden hacer para los demás rangos de edades.</p>
<p>Este mismo ejercicio se puede realizar para los hombres y hacer los mismos análisis. A continuación, se muestra el código computacional:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="estimación-de-proporciones.html#cb224-1" tabindex="-1"></a>sub_Hombre <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">edad_rango =</span> <span class="fu">case_when</span>(</span>
<span id="cb224-2"><a href="estimación-de-proporciones.html#cb224-2" tabindex="-1"></a>                      Age<span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">35</span>  <span class="sc">~</span> <span class="st">&quot;18 - 35&quot;</span>,<span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;Otro&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb224-3"><a href="estimación-de-proporciones.html#cb224-3" tabindex="-1"></a>                      <span class="fu">group_by</span>(edad_rango, Employment) <span class="sc">%&gt;%</span> </span>
<span id="cb224-4"><a href="estimación-de-proporciones.html#cb224-4" tabindex="-1"></a>                      <span class="fu">summarise</span>(<span class="at">Prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb224-5"><a href="estimación-de-proporciones.html#cb224-5" tabindex="-1"></a>                      <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##   edad_rango Employment       Prop     Prop_se   Prop_low   Prop_upp
## 1    18 - 35 Unemployed 0.09637042 0.018215667 0.06584071 0.13895080
## 2    18 - 35   Inactive 0.08939940 0.016438321 0.06175556 0.12773290
## 3    18 - 35   Employed 0.81423018 0.022991735 0.76436394 0.85553799
## 4       Otro Unemployed 0.02606667 0.007175709 0.01506262 0.04474457
## 5       Otro   Inactive 0.15344056 0.019883462 0.11805657 0.19706023
## 6       Otro   Employed 0.38849664 0.020270309 0.34919327 0.42930563
## 7       Otro       &lt;NA&gt; 0.43199614 0.021111842 0.39076987 0.47418649</code></pre>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tamaño-de-población-y-subpoblaciones-en-encuestas-de-hogares.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tablas-cruzadas.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/psirusteam/2021ASDA/05-Categóricas.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["Análisis de encuestas con R.pdf", "Análisis de encuestas con R.epub", "Análisis de encuestas con R.mobi"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  },
  "tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
